### ISSUE TITLE
media-video/avidemux

### ISSUE THREAD

**Issue by alexanderustinov** [waebbl/waebbl-gentoo#100]
Greetings, media-video/avidemux fails for me with https://gist.github.com/alexanderustinov/b7d66979e259d225ef977bc745a35863

Changing following in avidemux/common/ADM_audioFilter/src/audiofilter_normalize.cpp from
```
#if defined (_WIN32) || defined (__HAIKU__)
#define POW10(x)   pow(10,x)
#elif defined(ADM_BSD_FAMILY) || defined(__sun__)
#define POW10(x) powf(10.0,x)
#else
#define POW10(x)  pow10f(x)
#endif
```
to
```
#if defined (_WIN32) || defined (__HAIKU__)
#define POW10(x)   pow(10,x)
#elif defined(ADM_BSD_FAMILY) || defined(__sun__)
#define POW10(x) powf(10.0,x)
#else
#define POW10(x)  powf(10.0,x)
#endif
```
allows to fix it. But i do not understand whether it is a right way or not.

**Comment by waebbl** [comment]
Hi, thanks for reporting this.
TBH, this ebuild shouldn't be in the repository at all, but rather in my local repo only. Might be, I will remove it.
Your patch looks good to me. From the man pages for pow10f, this function should not be used anymore in new programs. Technically, both definitions should perform the same task (with exception of rounding differences).
What I don't understand, both functions would need to `#include <math.h>`, so both should be found. One thing which could cause the error, is the `pow10f` function need `_GNU_SOURCE` to be defined, while `powf` doesn't.

**Comment by waebbl** [comment]
Could you successfully compile it with the fix? For me it now fails on another target
```
/var/tmp/portage/media-video/avidemux-2.7.0/work/avidemux_2.7.0/avidemux/qt4/ADM_jobs/src/ADM_jobControl.cpp: In constructor ‘jobWindow::jobWindow()’:
/var/tmp/portage/media-video/avidemux-2.7.0/work/avidemux_2.7.0/avidemux/qt4/ADM_jobs/src/ADM_jobControl.cpp:150:54: error: invalid use of incomplete type ‘class QAction’
    QAction *del = new  QAction(QString("Delete"),this);
                                                      ^
In file included from /usr/include/qt5/QtWidgets/QWidget:1,
                 from /var/tmp/portage/media-video/avidemux-2.7.0/work/avidemux_2.7.0/avidemux/qt4/ADM_jobs/src/../include/T_jobs.h:4,
                 from /var/tmp/portage/media-video/avidemux-2.7.0/work/avidemux_2.7.0/avidemux/qt4/ADM_jobs/src/ADM_jobControl.cpp:14:
/usr/include/qt5/QtWidgets/qwidget.h:68:7: note: forward declaration of ‘class QAction’
 class QAction;
       ^~~~~~~
```

**Comment by waebbl** [comment]
I also found this https://bugs.gentoo.org/646494
So this bug has already been fixed in the gentoo tree.

**Comment by alexanderustinov** [comment]
Yes, it compiles now, thank you.
