### ISSUE TITLE
waebbl opencascade environment missing leading slash "/" in many paths.

### ISSUE THREAD

**Issue by stingray427** [waebbl/waebbl-gentoo#111]
/etc/env.d/51opencascade
lacks in many places leading zero.
for example:
`CASROOT=usr/lib64/opencascade-7.3.0/ros`

but in reality it should be rather:
`CASROOT=/usr/lib64/opencascade-7.3.0/ros`

I have suspicion in file waebbl-gentoo/sci-libs/opencascade/files/opencascade.env.in
VAR_CASROOT is "usr/lib64/opencascade-7.3.0/ros" instead of "/usr/lib64/opencascade-7.3.0/ros"

Anyway, after manually editing values (adding "/"), env-update and restarting allowed me to to continue with compiling freecad-0.18.2-r1 .

P.S.:
I think it should be a bug-report, but not sure how it would be useful, when opencascade ITSELF installs without problem. So no useful build.log for that matter.

**Comment by waebbl** [comment]
@stingray427 Thanks for pointing this out! It's been due to changes in EAPI 7 where EROOT no longer contains a trailing slash, and so the values from `opencascade.env.in` file get replaced wrong. I overlooked this when switching to `EAPI=7`. Gonna fix it.
