### ISSUE TITLE
OpenCascade-7.4 is out.

### ISSUE THREAD

**Issue by Petross404** [waebbl/waebbl-gentoo#148]
Hi, OpenCascade 7.4 is out. Would the latest freecad get a benefit out of an updated ebuild?

https://www.opencascade.com/content/latest-release

**Comment by waebbl** [comment]
I'm already at it, see also https://bugs.gentoo.org/696596.
It's likely freecad will benefit from the new release, as they state they have stabilized and increased performance on some of the features used by freecad.

**Comment by SimonLitt** [comment]
Hi, your ebuild frecad-0.18.3 and my ebuild frecad-0.18.4 ( see: https://github.com/waebbl/waebbl-gentoo/issues/152#issuecomment-571976593 ) works well with sci-libs/opencascade-7.4.0 (~amd64) from gentoo overlay.

**Comment by Petross404** [comment]
> Hi, your ebuild frecad-0.18.3 and my ebuild frecad-0.18.4 ( see: [#152 (comment)](https://github.com/waebbl/waebbl-gentoo/issues/152#issuecomment-571976593) ) works well with sci-libs/opencascade-7.4.0 (~amd64) from gentoo overlay.

How about the live (9999) package?

**Comment by SimonLitt** [comment]
> How about the live (9999) package?
Hi, unfortunately, I have not tested the live package.

**Comment by Petross404** [comment]
Well, if a previous version of freecad works ok with newer opencascade, I don't see why live master could possibly fail.

**Comment by waebbl** [comment]
`sci-libs/opencascade-7.4.0` has been in Gentoo portage tree for some time. I'm closing this, as the opencascade gets removed from my tree, in favour of the Gentoo tree ebuilds, which I'm also maintaining.
