### ISSUE TITLE
freecad-9999 can't install freecad-xx.png : No such file or directory

### ISSUE THREAD

**Issue by Petross404** [waebbl/waebbl-gentoo#149]
```
Installing: /mnt/Volume_3/Gentoo/temp/portage/media-gfx/freecad-9999/image/usr/share/freecad/data/examples/PartDesignExample.FCStd
-- Installing: /mnt/Volume_3/Gentoo/temp/portage/media-gfx/freecad-9999/image/usr/share/freecad/data/examples/RobotExample.FCStd
-- Installing: /mnt/Volume_3/Gentoo/temp/portage/media-gfx/freecad-9999/image/usr/share/freecad/data/examples/ArchDetail.FCStd
-- Installing: /mnt/Volume_3/Gentoo/temp/portage/media-gfx/freecad-9999/image/usr/share/freecad/data/examples/FemCalculixCantilever2D.FCStd
-- Installing: /mnt/Volume_3/Gentoo/temp/portage/media-gfx/freecad-9999/image/usr/share/freecad/data/examples/FemCalculixCantilever3D.FCStd
-- Installing: /mnt/Volume_3/Gentoo/temp/portage/media-gfx/freecad-9999/image/usr/share/freecad/data/examples/FemCalculixCantilever3D_newSolver.FCStd
rm: cannot remove '/mnt/Volume_3/Gentoo/temp/portage/media-gfx/freecad-9999/image/usr/share/freecad/data/freecad-doc.png': No such file or directory
rm: cannot remove '/mnt/Volume_3/Gentoo/temp/portage/media-gfx/freecad-9999/image/usr/share/freecad/data/freecad-icon-16.png': No such file or directory
rm: cannot remove '/mnt/Volume_3/Gentoo/temp/portage/media-gfx/freecad-9999/image/usr/share/freecad/data/freecad-icon-32.png': No such file or directory
rm: cannot remove '/mnt/Volume_3/Gentoo/temp/portage/media-gfx/freecad-9999/image/usr/share/freecad/data/freecad-icon-48.png': No such file or directory
rm: cannot remove '/mnt/Volume_3/Gentoo/temp/portage/media-gfx/freecad-9999/image/usr/share/freecad/data/freecad-icon-64.png': No such file or directory
 * ERROR: media-gfx/freecad-9999::waebbl failed (install phase):
 *   (no error message)
 * 
 * Call stack:
 *     ebuild.sh, line 125:  Called src_install
 *   environment, line 4418:  Called die
 * The specific snippet of code:
 *       rm "${ED}"/usr/share/${PN}/data/${PN}-{doc,icon-{16,32,48,64}}.png || die;

```
The live version of freecad is compiled but can't be installed due to missing (?) files.

**Comment by waebbl** [comment]
Looks like upstream has moved the install path of their icons. Unfortunately I don't have the resources to keep the live ebuild updated in a way it should be. It's better to stick to the versioned ebuild.
I'm looking into this, but currently don't have much time, due to other projects running.

**Comment by Petross404** [comment]
Yeah, I thought so but since the latest versioned ebuild installs a non-working freecad for me, I thought I could give a shot at the latest freecad. Thanks anyway.

**Comment by shredator27** [comment]
how much of a bounty would make it worth your while?  I'd really like a working 9999 build...

**Comment by kshots** [comment]
Looks to me more like they cleaned things up upstream. Your ebuild removes images from the destination image, but upstream no longer installs them. Commenting out the 3 "rm" lines (lines 280-282) should allow it to install.

1. The .png files are no longer installed
2. Upstream no longer installs the .svg to freecad - appears to now reside in a more system-centric location (/usr/share/icons/hicolor/scalable/apps/freecad.svg & /usr/$(libdir)/freecad/share/icons/hicolor/scalable/apps/freecad.svg)
3. Upstream no longer installs the .xpm to freecad - appears to now reside in a more system-centric location (/usr/share/pixmaps/freecad.xpm & /usr/$(libdir)/freecad/share/pixmaps/freecad.xpm)

**Comment by kshots** [comment]
Weird... appears not to only be a problem in the e-build but also upstream - their install script is failing for the same reason this ebuild would if those lines are not commented out. Apparently their install script is also trying to remove those files after installing (at least on my system after making those changes).

**Comment by Petross404** [comment]
Is there anything relevant in their forums?

**Comment by waebbl** [comment]
Thanks @kshots, @Petross404 for helping in this. Currently I can't even compile this with my default settings. I needed to disable the assembly USE flag to get it compiled.
@kshots have you ran ebuild clean after your changes? Portage uses the cached environment.
Looks like I fixed it, I'd be happy if you can test it. Posting the PR soon.

**Comment by waebbl** [comment]
If someone please could test the PR #151 
Thank you.

**Comment by kshots** [comment]
Yeah, that fixed it. Turns out I had a higher priority overlay (my local overlay) confusing things as I was poking at this ebuild, that's why my changes didn't seem to change it. I feel like an idiot :/. Your PR #151  fixed it for me.
