### ISSUE TITLE
Python support in libmed

### ISSUE THREAD

**Issue by waebbl** [waebbl/waebbl-gentoo#15]
python doesn't find the modules, althought they're installed in site-packages...

**Comment by waebbl** [comment]
```
waebbl@artus /mnt/data/code/github/portage-overlays/waebbl/sci-libs/libmed $ python
Python 3.6.5 (default, Jul  1 2018, 21:09:57) 
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import med
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib64/python3.6/site-packages/med/__init__.py", line 66, in <module>
    from .medequivalence import *
  File "/usr/lib64/python3.6/site-packages/med/medequivalence.py", line 555, in <module>
    import medenum
ModuleNotFoundError: No module named 'medenum'
>>> 
```

**Comment by waebbl** [comment]
When ran from /usr/lib63/python3.6/site-packages/med python will find the file

**Comment by waebbl** [comment]
Changing `import medenum` to `from . import medenum` leads to

```
waebbl@artus /mnt/data/code/github/devmanual.gentoo.org $ python
Python 3.6.5 (default, Jul  1 2018, 21:09:57) 
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import med
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib64/python3.6/site-packages/med/__init__.py", line 67, in <module>
    from .medfamily import *
  File "/usr/lib64/python3.6/site-packages/med/medfamily.py", line 555, in <module>
    import medenum
ModuleNotFoundError: No module named 'medenum'
>>> 
```

**Comment by waebbl** [comment]
Again changing to `from . import medenum` in medfamily.py leads to

```
Python 3.6.5 (default, Jul  1 2018, 21:09:57) 
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import med
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib64/python3.6/site-packages/med/__init__.py", line 68, in <module>
    from .medfield import *
  File "/usr/lib64/python3.6/site-packages/med/medfield.py", line 555, in <module>
    import medenum
ModuleNotFoundError: No module named 'medenum'
>>> 
```

**Comment by waebbl** [comment]
Same for medfield.py, medfile.py, medfilter.py, medinterp.py, medlibrary.py, medlink.py, medlocalization.py, medmesh.py, medparameter.py and medprofile.py.

Check whether this comes from the swigfiles or from a bug in swig and report upstream or file a swig bug report.

**Comment by waebbl** [comment]
Upstream seems to be EDF in France, salome-platform is just using libmed with their software, although they currently have sources for version 3.3.1 for download. 
Original download site at EDF is no longer available (see https://forum.freecadweb.org/viewtopic.php?f=8&t=31095)

**Comment by waebbl** [comment]
Upstream response to freecad forum question: https://dev.opencascade.org/index.php?q=node/1217

**Comment by jborme** [comment]
Don't know if connected, but I just tried to emerge libmed from the overlay and it fails with:
sed: can't read /var/tmp/portage/portage/sci-libs/libmed-3.3.1/work/libmed-3.3.1_build/python/med/*.py: No such file or directory

**Comment by waebbl** [comment]
@jborme I think this hasn't to do with the issue.

Anyway, which USE flags did you use? It looks like an issue related to the `python` USE flag. Could you please provide the output of `emerge --info =sci-libs/libmed-3.3.1::waebbl`?

**Comment by jborme** [comment]
Your recent commit 618e0b0 / commit ea496aa solved the problem. FYI the emerge --info you asked for. [emerge--info_sci-libs_libmed-3.3.1_waebbl.txt](https://github.com/waebbl/waebbl-gentoo/files/2545820/emerge--info_sci-libs_libmed-3.3.1_waebbl.txt)

**Comment by waebbl** [comment]
@jborme So it was related to the use of `python` USE flag.
Thanks for reporting :+1:

**Comment by waebbl** [comment]
The package has been removed and is now available on Gentoo tree as sci-libs/med.
Closing this.
