### ISSUE TITLE
Update freecad to 0.18.4

### ISSUE THREAD

**Issue by waebbl** [waebbl/waebbl-gentoo#152]
Upstream released 0.18.4 some time ago.

**Comment by SimonLitt** [comment]
Hi,
I made a ebuild for version 0.18.4. I took ebuild version 0.18.3::waebbl  as a basis. Installation was successful. So far I have not noticed problems in the program.
Build log and ebuild in the attachment.
[build.tar.gz](https://github.com/waebbl/waebbl-gentoo/files/4034653/build.tar.gz)
[freecad.tar.gz](https://github.com/waebbl/waebbl-gentoo/files/4034654/freecad.tar.gz)

**Comment by waebbl** [comment]
Hi @SimonLitt, thanks for your efforts. I already have a 0.18.4 ebuild in a development branch, but had some trouble with my stable `amd64` installation. I'm currently in the process of upgrading my machine to `~amd64`, but it's a troublesome and time consuming process, which will probably take a few additional days.
After this, I'm going to test again and compare with your ebuild and submit the new ebuild.
