### ISSUE TITLE
media-gfx/freecad-9999 needs dev-qt/qtxmlpatterns

### ISSUE THREAD

**Issue by Petross404** [waebbl/waebbl-gentoo#154]
**Describe the bug**
Latest freecad can't be configured without qtxmlpatterns

```
  Could not find a package configuration file provided by "Qt5XmlPatterns"
  with any of the following names:

    Qt5XmlPatternsConfig.cmake
    qt5xmlpatterns-config.cmake

  Add the installation prefix of "Qt5XmlPatterns" to CMAKE_PREFIX_PATH or set
  "Qt5XmlPatterns_DIR" to a directory containing one of the above files.  If
  "Qt5XmlPatterns" provides a separate development package or SDK, be sure it
  has been installed.
 Call Stack (most recent call first):
  CMakeLists.txt:68 (include)
```

[media-gfx:freecad-9999:20191116-203007.log](https://github.com/waebbl/waebbl-gentoo/files/3855409/media-gfx.freecad-9999.20191116-203007.log)

**Additional context**
Installing this package allows freecad to be configured.

**Comment by waebbl** [comment]
Thanks @Petross404. I'm looking into this.

**Comment by Petross404** [comment]
Nice, thank you for all the work you are doing.
