### ISSUE TITLE
sci-libs/pcl headers are causing freecad compilation to fail.

### ISSUE THREAD

**Issue by Petross404** [waebbl/waebbl-gentoo#155]
**Describe the bug**
Emerging freecad-9999 with assembly use flag fails to build.

[media-gfx:freecad-9999:20191207-071718.log](https://github.com/waebbl/waebbl-gentoo/files/3935101/media-gfx.freecad-9999.20191207-071718.log)

**Additional context**
I noticed there is an error about `auto` c++ keywords that needs C++14 too.

**Comment by waebbl** [comment]
Thanks for reporting this @Petross404. Which version of gcc did you use (for both pcl and freecad)?

**Comment by Petross404** [comment]
I am using gcc version 9.2 for all the packages. I think it pulled the pcl of your repo, but since I am away from my pc I can't give you a certain answer.

**Comment by waebbl** [comment]
Closing. Assembly USE flag has long been gone and the old assembly workbench is treated obsolete by upstream. Please consider using assembly3 or assembly4 workbench.
