### ISSUE TITLE
little problem in 9999 build

### ISSUE THREAD

**Issue by CaptainBloodz** [waebbl/waebbl-gentoo#156]
Emerging (1 of 1) media-gfx/freecad-9999::waebbl
 * Checking for at least 6.5 GiB disk space at "/var/no-tmpfs/portage/media-gfx/freecad-9999/temp" ...
/usr/portage/eclass/check-reqs.eclass: line 165: 6.5: syntax error: invalid arithmetic operator (error token is ".5")

**Comment by waebbl** [comment]
Thanks for reporting this @CaptainBloodz. Looks like bash can handle only integers in arithmetic expressions. I'm going to round this to an integer.
