### ISSUE TITLE
freecad-0.18.3: doc files integration incomplete

### ISSUE THREAD

**Issue by CaptainBloodz** [waebbl/waebbl-gentoo#157]
In order to have F1 working, I had to:

install  dev-qt/assistant.

extract in-place the 2 following files located in /usr/share/doc/freecad-0.18.3:
freecad.qhc.lzma
freecad.qch.lzma

**Comment by waebbl** [comment]
Thanks for the hint @CaptainBloodz. I'm looking into this and integrate it in the build process.
