### ISSUE TITLE
We need freecad-0.17 git

### ISSUE THREAD

**Issue by brothermechanic** [waebbl/waebbl-gentoo#16]
Hello
Plase, can you comment EGIT_BRANCH="master" in freecad-9999.ebuild, this give me possible to install 0.17 branch too 
(some plugins still don't ported to freecad)

**Comment by waebbl** [comment]
No, first you want it commented, then uncommented, now again commented. You can easily do this with your local copy. The repository needs some stability and not changed just for this. That's just confusing anyone who might use the repo as well.

Btw. you won't have much luck installing the 0.17 branch on gentoo. It needs Qt4 which isn't available anymore in the tree.

**Comment by brothermechanic** [comment]
ok. as you wish
