### ISSUE TITLE
assembly USE flag change?

### ISSUE THREAD

**Issue by CaptainBloodz** [waebbl/waebbl-gentoo#162]
user@amd64 ~ $ eix freecad
[I] media-gfx/freecad [1]
     Installed versions:  0.18.3(12:12:19 16/12/2019)(addonmgr arch assembly complete doc drawing fem idf image inspection material mesh openscad part_design path pcl points raytracing reverseengineering robot ship show spreadsheet surface techdraw tux -debug -mpi -netgen PYTHON_SINGLE_TARGET="python3_6" PYTHON_TARGETS="python3_6")

user@amd64 ~ $ euse freecad
[ Legend : U - final flag setting for installation]
[        : I - package is installed with flag     ]
[ Colors : set, unset                             ]
 * Found these USE flags for media-gfx/freecad-0.18.3:
 U I
 + + addonmgr                       : Build the addon manager module for automatic handling of 3rd party addons 
 + + arch                           : Build the architecture workbench for working with architectural elements 
 + + assembly                       : Build the assembly module 
 + + complete                       : Build the complete workbench which holds all commands and features from all the modules and workbenches
                                      which met certain quality criteria 
 - - debug                          : Enable extra debug codepaths, like asserts and extra output. If you want to get meaningful backtraces
                                      see https://wiki.gentoo.org/wiki/Project:Quality_Assurance/Backtraces
 + + doc                            : Add extra documentation (API, Javadoc, etc). It is recommended to enable per package instead of globally
 + + drawing                        : Build the drawing module and workbench to display 3D work on a 2D sheet 
 + + fem                            : Build the FEM module and workbench which provides Finite Element Analysis (FEA) workflows 
 + + idf                            : Build the IDF module to provide file exchange capabilities with IDF files 
 + + image                          : Build the image module and workbench for working with bitmap images 
 + + inspection                     : Build the inspection workbench which gives you specific tools for examination of shapes (experimental) 
 + + material                       : Build the material module and workbench to work with materials 
 + + mesh                           : Build the mesh module and workbench to work with triangulated meshes 
 - - mpi                            : Add MPI (Message Passing Interface) layer to the apps that support it
 + - netgen                         : Support sci-mathematics/netgen with the FEM workbench 
 + + openscad                       : Build the OpenSCAD module for interoperability with OpenSCAD and repairing Constructive Solid Geometry
                                      (CSG) history 
 + + part_design                    : Build the part design module and workbench for build part shapes from sketches 
 + + path                           : Build the path module and workbench to procude G-Code instructions for CNC 
 + + pcl                            : Use external sci-libs/pcl for point clouds support. 
 + + points                         : Build the points module and workbench for working with point clouds 
 + + python_single_target_python3_6 : Build for Python 3.6 only
 + + python_targets_python3_6       : Build with Python 3.6
 + + raytracing                     : Build the raytracing module and workbench for raytracing and rendering 
 + + reverseengineering             : Build the reverse engineering module and workbench which provides specific tools to convert
                                      shapes/solids/meshes into parametric FreeCAD-compatible features 
 + + robot                          : Build the robot module and workbench for studying robot movements 
 + + ship                           : Build the ship module and workbench which works over ship entities, that must be created on top of
                                      provided geometry 
 + + show                           : Build the show module, a helper module for visibility automation 
 + + spreadsheet                    : Build the spreadsheet module and workbench to create and manipulate spreadsheet data 
 + + surface                        : Build the surface module and workbench 
 + + techdraw                       : Build the techdraw module and workbench, a more advanced and feature-rich successor of the drawing
                                      workbench 
 + + tux                            : Build the Tux module 
user@amd64 ~ $ emerge -p freecad

These are the packages that would be merged, in reverse order:

Calculating dependencies  
... done!
[ebuild   R   ~] media-gfx/freecad-0.18.3  USE="(-assembly*)" 
----------------------------------------------------------------------------------------------------------------------------------
freecad builded fine with assembly enabled.
Not using freecad yet, so I have no idea how usable.

**Comment by waebbl** [comment]
@CaptainBloodz, if it build with `USE=assembly` you were probably lucky. I tested it last with 0.18.0, where it did also work, but it doesn't build with current code base and will probably cause issues with later versions too. So I decided to disable it for now, until the assembly code has been fixed upstream.

Please refer to https://www.freecadweb.org/tracker/view.php?id=4145 and https://forum.freecadweb.org/viewtopic.php?f=4&t=39716 for the issue.

**Comment by CaptainBloodz** [comment]
Well, I haven"t rebuilded for mpi yet.
While doing so I'd rather keep that assembly USE flag enabled and active.
Is that possible? What should I do?

**Comment by CaptainBloodz** [comment]
Replicating to local overlay did the trick.

**Comment by waebbl** [comment]
@CaptainBloodz Note, the assembly USE flag will be ignored by the current ebuilds, so it doesn't change anything, whether you have it enabled or not, the ebuild will not build the assembly workspace.
