### ISSUE TITLE
Flags dependencies required here for minimal build

### ISSUE THREAD

**Issue by CaptainBloodz** [waebbl/waebbl-gentoo#163]
* Found these USE flags for dev-libs/libspnav-0.2.3:
 U I
 + + X : Add support for X11
-------------------------------------------------------------------------------------------------------------------------
Found these USE flags for media-libs/coin-4.0.0a_pre20181221:
 U I
 + + vrml97       : Enables VRML97 support
-------------------------------------------------------------------------------------------------------------------------
Couldn't build minimal freecad without these two flags enabled.
Find out the hard way through errors.log.

As you seem to be preparing freecad to return to main portage tree, you might be interest to check out on your side.

Thks 4 ur attention.

**Comment by waebbl** [comment]
@CaptainBloodz thanks for reporting this. Did you use the versioned ebuild, i.e. 0.18.3 or the live ebuild?

**Comment by CaptainBloodz** [comment]
Installed versions:  0.18.3(12:12:19 16/12/2019)(addonmgr arch assembly complete doc drawing fem idf image inspection material mesh openscad part_design path pcl points raytracing reverseengineering robot ship show spreadsheet surface techdraw tux -debug -mpi -netgen PYTHON_SINGLE_TARGET="python3_6" PYTHON_TARGETS="python3_6")

**Comment by waebbl** [comment]
@CaptainBloodz Ok, I'm trying to reproduce this.

**Comment by SimonLitt** [comment]
> Found these USE flags for media-libs/coin-4.0.0a_pre20181221:
> U I
> 
>     * * vrml97       : Enables VRML97 support
> 
Freecad 0.18.3 and 0.18.4 emerge and work well  with media-libs/coin-4.0.0a_pre20191109 (~amd64) from gentoo overlay. There are no the USE flag at this ebuild. This option is always enabled.
