### ISSUE TITLE
Couldn't build twice in a row in the same X terminal session

### ISSUE THREAD

**Issue by CaptainBloodz** [waebbl/waebbl-gentoo#164]
I suspect initial build to change something in the environment which will block the second build.
Please note that building for the second time does succeed from an alternate terminal.

**Comment by waebbl** [comment]
@CaptainBloodz Please be more specific, what leads the build to fail, which errors (build log).
Also note, I have an issue template, please use this for **ALL** issues, you haven't used it once.
Normally the environment isn't changed by an ebuild, as it completely runs inside a sandbox. May it be, your environment has settings which could lead such behaviour?
