### ISSUE TITLE
freecad depends on X useflag for libspnav

### ISSUE THREAD

**Issue by ChrisOboe** [waebbl/waebbl-gentoo#170]
See title. 
When libspnav is build without X useflag the compilation of freecad will fail.

**Comment by waebbl** [comment]
@ChrisOboe thanks for the report. I probably didn't checked this, as most people who want to use freecad, will have X enabled anyway. I'll check it.

**Comment by Perlovka** [comment]
X could be enabled per package, not global, so I think dev-libs/libspnav[X] is required.
