### ISSUE TITLE
Update dev-python/shiboken to 5.13.2

### ISSUE THREAD

**Issue by SimonLitt** [waebbl/waebbl-gentoo#172]
Ebuild at the attachment
[shiboken-5.13.2.ebuild.tar.gz](https://github.com/waebbl/waebbl-gentoo/files/4035496/shiboken-5.13.2.ebuild.tar.gz)

**Comment by waebbl** [comment]
@SimonLitt Thanks for your contributions.
I will wait with the Qt for Python related updates, until we have more consensus on how to proceed with this at b.g.o. See https://bugs.gentoo.org/622726
There's an overlay `::raiagent` which has more up to date ebuilds for those packages, therefore, for now I've added the `don't merge` tag to this issue.
