### ISSUE TITLE
FreeCAD workbenches to build by default

### ISSUE THREAD

**Issue by Perlovka** [waebbl/waebbl-gentoo#183]
Hi,

There are some workbenches that should not be built by default, they are empty or deprecated:

- complete (deprecated: https://www.freecadweb.org/wiki/Complete_Workbench)
- reverseengineering (empty: https://www.freecadweb.org/wiki/Reverse_Engineering_Workbench)
- ship and plot (should not be built to be able to use extrernal workbenches https://github.com/FreeCAD/FreeCAD/pull/2147 )
- test (used for debug purposes, should be built with debug USE-flag enabled, IMO: https://www.freecadweb.org/wiki/Testing )
`-DBUILD_TEST=$(usex debug)`

**Comment by waebbl** [comment]
@Perlovka thanks for the pointers! I'm currently working on 0.18.4 and will use your pointers to select default USE flags.
By now, I have been using the values from the cmakefiles to select the defaults. For some cases, upstream uses unusual settings when it comes to default options...
