### ISSUE TITLE
media-gfx/freecad-0.18.3: ebuild issue due to portage changes

### ISSUE THREAD

**Issue by CaptainBloodz** [waebbl/waebbl-gentoo#190]
The following installed packages are masked:
- media-gfx/freecad-0.18.3::local-repo (masked by: invalid: BDEPEND: Invalid atom (Invalid use dep: '%PYTHON_USEDEP-HAS-BEEN-REMOVED%'), token 1 in '/var/db/pkg/media-gfx/freecad-0.18.3/BDEPEND', invalid: DEPEND: Invalid atom (Invalid use dep: '%PYTHON_USEDEP-HAS-BEEN-REMOVED%'), token 8 in '/var/db/pkg/media-gfx/freecad-0.18.3/DEPEND', invalid: RDEPEND: Invalid atom (Invalid use dep: '%PYTHON_USEDEP-HAS-BEEN-REMOVED%'), token 8 in '/var/db/pkg/media-gfx/freecad-0.18.3/RDEPEND')

No idea if due to an error or to be considered as reliable.
Thks 4 ur attention.

**Comment by clytle374** [comment]
Not sure if this should be a separate issue, or not, but it's getting some other packages with it. 
This issue is blocking openvdb and vtk also.  
Thanks
Cory

**Comment by waebbl** [comment]
Ok, I think this is because of https://github.com/gentoo/gentoo/pull/14589
It affects all packages inheriting python-single-r1.eclass.
I'll look into it, but will probably not able to do it, until next week.

**Comment by clytle374** [comment]
> Ok, I think this is because of [gentoo/gentoo#14589](https://github.com/gentoo/gentoo/pull/14589)
> It affects all packages inheriting python-single-r1.eclass.
> I'll look into it, but will probably not able to do it, until next week.

We appreciate your efforts
Thanks
Cory

**Comment by ElDavoo** [comment]
It should be a trivial change, just removing all PYTHON_USEDEP references from ebuilds.

**Comment by waebbl** [comment]
It's not that simple. If you look at one of the changes already in the tree, for example https://github.com/gentoo/gentoo/commit/78d46b5ed652734487e07c9ffd7e697d4cc5f947 you'll see.

**Comment by CaptainBloodz** [comment]
Hi
[freecad-0.18.3-r1.ebuild.zip](https://github.com/waebbl/waebbl-gentoo/files/4200651/freecad-0.18.3-r1.ebuild.zip)
vtk, netgen & pybind11 almost done, a little versionning issue remains to be solved (seems due to replication of pybind11 to local repo).
Thks 4 ur attention.

**Comment by CaptainBloodz** [comment]
Hi
[freecad-0.18.3-r1.ebuild.zip](https://github.com/waebbl/waebbl-gentoo/files/4200867/freecad-0.18.3-r1.ebuild.zip)
[netgen-6.2.1810-r1.ebuild.zip](https://github.com/waebbl/waebbl-gentoo/files/4200871/netgen-6.2.1810-r1.ebuild.zip)
[pybind11-2.2.4-r1.ebuild.zip](https://github.com/waebbl/waebbl-gentoo/files/4200872/pybind11-2.2.4-r1.ebuild.zip)
[vtk-8.2.0-r1.ebuild.zip](https://github.com/waebbl/waebbl-gentoo/files/4200873/vtk-8.2.0-r1.ebuild.zip)
Thks 4 ur attention

**Comment by CaptainBloodz** [comment]
rebuilding freecad-9.18.3-r1 here, almost went fine:
scanelf: rpath_security_checks(): Security problem NULL DT_RUNPATH in /var/no-tmpfs/portage/media-gfx/freecad-0.18.3-r1/image/usr/lib64/freecad/lib64/libDriver.so
scanelf: rpath_security_checks(): Security problem NULL DT_RUNPATH in /var/no-tmpfs/portage/media-gfx/freecad-0.18.3-r1/image/usr/lib64/freecad/lib64/libMEFISTO2.so
scanelf: rpath_security_checks(): Security problem NULL DT_RUNPATH in /var/no-tmpfs/portage/media-gfx/freecad-0.18.3-r1/image/usr/lib64/freecad/lib64/libSMDS.so
Auto fixing rpaths for /var/no-tmpfs/portage/media-gfx/freecad-0.18.3-r1/image/usr/lib64/freecad/lib64/libDriver.so
Auto fixing rpaths for /var/no-tmpfs/portage/media-gfx/freecad-0.18.3-r1/image/usr/lib64/freecad/lib64/libMEFISTO2.so
Auto fixing rpaths for /var/no-tmpfs/portage/media-gfx/freecad-0.18.3-r1/image/usr/lib64/freecad/lib64/libSMDS.so

 * QA Notice: The following files contain insecure RUNPATHs
 *  Please file a bug about this at https://bugs.gentoo.org/
 *  with the maintainer of the package.
 *   /var/no-tmpfs/portage/media-gfx/freecad-0.18.3-r1/image/usr/lib64/freecad/lib64/libDriver.so
 *     RPATH: :/usr/lib64
 *   /var/no-tmpfs/portage/media-gfx/freecad-0.18.3-r1/image/usr/lib64/freecad/lib64/libMEFISTO2.so
 *     RPATH: :/usr/lib64
 *   /var/no-tmpfs/portage/media-gfx/freecad-0.18.3-r1/image/usr/lib64/freecad/lib64/libSMDS.so
 *     RPATH: :/usr/lib64
 *

**Comment by clytle374** [comment]
Are the changes to vtk online now?
Thanks
Cory

**Comment by CaptainBloodz** [comment]
I don't think so, although I don't know.
Maybe it's time for homework with what's provided above.
Alternatively, wait for waebbl to get things ready for you, the easy way.
Thks 4 ur attention.

**Comment by clytle374** [comment]
I've already broke my Gentoo once today, I can wait. lol

**Comment by nick87720z** [comment]
Exactly, it affects any packages, using python-single-r1 (at least). According to new eclass docs,
there are now PYTHON_SINGLE_USEDEP for dependencies, using python-single-r1 and PYTHON_MULTI_USEDEP for those, using just python-r1.
So, just grep for python-single-r1.
