### ISSUE TITLE
media-gfx/freecad-0.18.4-r1 build error

### ISSUE THREAD

**Issue by CaptainBloodz** [waebbl/waebbl-gentoo#194]
```
equery u freecad 
[ Legend : U - final flag setting for installation]
[        : I - package is installed with flag     ]
[ Colors : set, unset                             ]
 * Found these USE flags for media-gfx/freecad-0.18.4-r1:
 U I
 + - addonmgr                       : Build the addon manager module for automatic handling of 3rd party addons 
 + - arch                           : Build the architecture workbench for working with architectural elements 
 + - assembly                       : Build the assembly module 
 - - debug                          : Enable extra debug codepaths, like asserts and extra output. If you want to get meaningful backtraces see
                                      https://wiki.gentoo.org/wiki/Project:Quality_Assurance/Backtraces
 + - doc                            : Add extra documentation (API, Javadoc, etc). It is recommended to enable per package instead of globally
 + - drawing                        : Build the drawing module and workbench to display 3D work on a 2D sheet 
 + - fem                            : Build the FEM module and workbench which provides Finite Element Analysis (FEA) workflows 
 + - idf                            : Build the IDF module to provide file exchange capabilities with IDF files 
 + - image                          : Build the image module and workbench for working with bitmap images 
 + - inspection                     : Build the inspection workbench which gives you specific tools for examination of shapes (experimental) 
 + - material                       : Build the material module and workbench to work with materials 
 + - mesh                           : Build the mesh module and workbench to work with triangulated meshes 
 + - mpi                            : Add MPI (Message Passing Interface) layer to the apps that support it
 + - netgen                         : Support sci-mathematics/netgen with the FEM workbench 
 + - openscad                       : Build the OpenSCAD module for interoperability with OpenSCAD and repairing Constructive Solid Geometry (CSG) history 
 + - part_design                    : Build the part design module and workbench for build part shapes from sketches 
 + - path                           : Build the path module and workbench to procude G-Code instructions for CNC 
 + - pcl                            : Use external sci-libs/pcl for point clouds support. 
 + - plot                           : Build the internal plot workbench. NOTE: This conflicts with the external plot workbench, which you can add via the
                                      Addon Manager! 
 + - points                         : Build the points module and workbench for working with point clouds 
 + - python_single_target_python3_6 : Build for Python 3.6 only
 + - raytracing                     : Build the raytracing module and workbench for raytracing and rendering 
 + - robot                          : Build the robot module and workbench for studying robot movements 
 + - ship                           : Build the ship module and workbench which works over ship entities, that must be created on top of provided geometry.
                                      NOTE: This conflicts with the external ship workbench, which you can add via the Addon Manager! 
 + - show                           : Build the show module, a helper module for visibility automation 
 + - spreadsheet                    : Build the spreadsheet module and workbench to create and manipulate spreadsheet data 
 + - surface                        : Build the surface module and workbench 
 + - techdraw                       : Build the techdraw module and workbench, a more advanced and feature-rich successor of the drawing workbench 
 + - tux                            : Build the Tux module 
```
------------------------------------------------------------------------
```
eix virtual/mpi
[I] virtual/mpi
     Installed versions:  2.0-r5(12:26:01 28/12/2019)(cxx fortran romio threads ABI_MIPS="-n32 -n64 -o32" ABI_RISCV="-lp64 -lp64d" ABI_S390="-32 -64" ABI_X86="64 -32 -x32")
```
------------------------------------------------------------------------
```
eix sys-cluster/openmpi
[I] sys-cluster/openmpi
     Installed versions:  2.0.2(12:25:47 28/12/2019)(cma cxx fortran heterogeneous mpi-threads romio threads -cuda -ipv6 -java -numa ABI_MIPS="-n32 -n64 -o32" ABI_RISCV="-lp64 -lp64d" ABI_S390="-32 -64" ABI_X86="64 -32 -x32" ELIBC="-FreeBSD" OPENMPI_FABRICS="-knem -ofed -psm" OPENMPI_OFED_FEATURES="-connectx-xrc -control-hdr-padding -dynamic-sl -failover -rdmacm -udcm" OPENMPI_RM="-pbs -slurm")
```
------------------------------------------------------------------------
[media-gfx:freecad-0.18.4-r1:20200223-185546.log.zip](https://github.com/waebbl/waebbl-gentoo/files/4242209/media-gfx.freecad-0.18.4-r1.20200223-185546.log.zip)

Edit(waebbl): markdown formatting

**Comment by waebbl** [comment]
Thanks for the report. Please mark code/output properly in the future.
Before looking into the log file... You have `assembly` USE flag enabled, which is masked and won't compile.

**Comment by CaptainBloodz** [comment]
currently trying -assembly -netgen -plot.

**Comment by waebbl** [comment]
It will fail again, as long as you don't upgrade to qt-5.14!

I found some other output with respect to dependencies between workbenches in your logfile and will include these in the patch.

**Comment by CaptainBloodz** [comment]
Sorry for the noise.
Thks.

**Comment by stingray427** [comment]
actually I managed to compile freecad 0.18.4 from sources (not ebuild) on Qt 5.13.2

For some reason the CMake by FreeCAD detects <code>/usr/bin/rcc</code>, can't find it my cmake configuration again, but I am pretty sure I pointed DPYSIDE2RCCBINARY to <code>/usr/bin/pyrcc5</code> and only then I stopped getting
<code>rcc: Unknown option 'g'.</code>
Which is very annoying to spot, since it has no label "Error" near it. (I had to compile with 1 thread, to see where compilation aborts)

And i see same <code>rcc: Unknown option 'g'.</code> in the build-log of @CaptainBloodz .

>

**Comment by waebbl** [comment]
@CaptainBloodz you're welcome. No noise at all!

**Comment by waebbl** [comment]
I'm wondering which version of shiboken2 / pyside2 do you have installed?

**Comment by waebbl** [comment]
@CaptainBloodz can you please try whether PR #196 works?

**Comment by CaptainBloodz** [comment]
eix freecad
* app-doc/freecad-doc [1]
     Available versions:  **9999*l
     Homepage:            https://www.freecadweb.org/
     Description:         QT based computer aided design application manuals

[I] media-gfx/freecad
     Installed versions:  0.18.4-r1[1](08:25:40 25/02/2020)(addonmgr arch doc drawing fem idf image inspection material mesh mpi openscad part_design path pcl points raytracing robot ship show spreadsheet surface techdraw tux -assembly -debug -netgen -plot PYTHON_SINGLE_TARGET="python3_6")

As a side note, I had you remove pyside pyside-tools & shiboken prior to upgrade.
Maybe ebuild has been change accordlingly.

**Comment by waebbl** [comment]
Yes I know, but which version of pyside2, shiboken2 and pyside2-tools do you have installed?

**Comment by CaptainBloodz** [comment]
```eix pivy
[I] dev-python/pivy [1]
     Available versions:  (~)0.6.4 (~)0.6.5 ~9999 {PYTHON_TARGETS="python3_6 python3_7 python3_8"}
     Installed versions:  0.6.5(21:55:16 23/02/2020)(PYTHON_TARGETS="python3_6 -python3_7 -python3_8")
     Homepage:            http://pivy.coin3d.org/
     Description:         Coin3d bindings for Python

[1] "waebbl" /var/db/repos/waebbl
eix pyside2
luc@amd64 ~ $ eix pyside2
eix shiboken2
[I] dev-python/pyside2 [1]
     Available versions:  (~)5.12.5-r3^t ~5.14.0^t ~5.14.1^t {3d charts concurrent datavis designer gles2 gui help location multimedia network positioning printsupport qml quick script scripttools scxml sensors speech sql svg test testlib webchannel webengine websockets widgets x11extras xml xmlpatterns PYTHON_TARGETS="python2_7 python3_6 python3_7 python3_8"}
     Installed versions:  5.12.5-r3^t(21:45:35 23/02/2020)(gui svg widgets -3d -charts -concurrent -datavis -designer -gles2 -help -location -multimedia -network -positioning -printsupport -qml -quick -script -scripttools -scxml -sensors -speech -sql -test -testlib -webchannel -webengine -websockets -x11extras -xml -xmlpatterns PYTHON_TARGETS="python3_6 -python2_7 -python3_7")
     Homepage:            https://wiki.qt.io/PySide2
     Description:         Python bindings for the Qt framework

[I] dev-python/pyside2-tools [1]
     Available versions:  (~)5.12.5-r1^t ~5.14.0^t ~5.14.1^t {test tools PYTHON_TARGETS="python2_7 python3_6 python3_7 python3_8"}
     Installed versions:  5.12.5-r1^t(21:46:05 23/02/2020)(-test PYTHON_TARGETS="python3_6 -python2_7 -python3_7")
     Homepage:            https://wiki.qt.io/PySide2
     Description:         PySide development tools (lupdate, rcc, uic)

[1] "raiagent" /var/db/repos/raiagent

Found 2 matches
luc@amd64 ~ $ eix shiboken2
[I] dev-python/shiboken2 [1]
     Available versions:  (~)5.12.5-r3 ~5.14.0 ~5.14.1 {+docstrings numpy test PYTHON_TARGETS="python2_7 python3_6 python3_7 python3_8"}
     Installed versions:  5.12.5-r3(21:09:18 23/02/2020)(-docstrings -numpy -test PYTHON_TARGETS="python3_6 -python2_7 -python3_7")
     Homepage:            https://wiki.qt.io/PySide2
     Description:         Python binding generator for C++ libraries```

**Comment by CaptainBloodz** [comment]
> @CaptainBloodz can you please try whether PR #196 works?
No as I switched to Qt-14.1 in the mean time.

**Comment by waebbl** [comment]
So it's building with Qt-5.14?

**Comment by CaptainBloodz** [comment]
Indeed. and {pyside2,pyside-tools2,shiboken2}-5.12.x.
assembly and netgen builded fine too (can't tell about stability or feature, though).

**Comment by CaptainBloodz** [comment]
Little QA issue``` [32;01m*[0m Final size of build directory: 1130556 KiB (  1.0 GiB)
 [32;01m*[0m Final size of installed tree:   371624 KiB (362.9 MiB)

[31;01mscanelf[00;00m: [33;01mrpath_security_checks[00;00m(): Security problem NULL DT_RUNPATH in /var/no-tmpfs/portage/media-gfx/freecad-0.18.4-r1/image/usr/lib64/freecad/lib64/libDriver.so
[31;01mscanelf[00;00m: [33;01mrpath_security_checks[00;00m(): Security problem NULL DT_RUNPATH in /var/no-tmpfs/portage/media-gfx/freecad-0.18.4-r1/image/usr/lib64/freecad/lib64/libMEFISTO2.so
[31;01mscanelf[00;00m: [33;01mrpath_security_checks[00;00m(): Security problem NULL DT_RUNPATH in /var/no-tmpfs/portage/media-gfx/freecad-0.18.4-r1/image/usr/lib64/freecad/lib64/libSMDS.so
Auto fixing rpaths for /var/no-tmpfs/portage/media-gfx/freecad-0.18.4-r1/image/usr/lib64/freecad/lib64/libDriver.so
Auto fixing rpaths for /var/no-tmpfs/portage/media-gfx/freecad-0.18.4-r1/image/usr/lib64/freecad/lib64/libMEFISTO2.so
Auto fixing rpaths for /var/no-tmpfs/portage/media-gfx/freecad-0.18.4-r1/image/usr/lib64/freecad/lib64/libSMDS.so

 [33;01m*[0m QA Notice: The following files contain insecure RUNPATHs
 [33;01m*[0m  Please file a bug about this at https://bugs.gentoo.org/
 [33;01m*[0m  with the maintainer of the package.
 [33;01m*[0m   /var/no-tmpfs/portage/media-gfx/freecad-0.18.4-r1/image/usr/lib64/freecad/lib64/libDriver.so
 [33;01m*[0m     RPATH: :/usr/lib64
 [33;01m*[0m   /var/no-tmpfs/portage/media-gfx/freecad-0.18.4-r1/image/usr/lib64/freecad/lib64/libMEFISTO2.so
 [33;01m*[0m     RPATH: :/usr/lib64
 [33;01m*[0m   /var/no-tmpfs/portage/media-gfx/freecad-0.18.4-r1/image/usr/lib64/freecad/lib64/libSMDS.so
 [33;01m*[0m     RPATH: :/usr/lib64
 [33;01m*[0m

**Comment by waebbl** [comment]
I know, they are even noted in the ebuild in src_configure, when checking for `if use mpi; then` ;)

Due to limited ressources, and more important issues, I haven't had the time to look into this. Ideally smesh would be build externally, but it's part of huge package Salome Platform, which is on my todo list to get it included in my overlay, but again, limited ressources delay this.

**Comment by waebbl** [comment]
> Indeed. and {pyside2,pyside-tools2,shiboken2}-5.12.x.
> assembly and netgen builded fine too (can't tell about stability or feature, though).

Nice! :) There's an upcoming patch for this, which checks for pyside2-tools or qtcore versions being installed and optionally applies the patch to use the generator option to rcc.

**Comment by waebbl** [comment]
> assembly and netgen builded fine too (can't tell about stability or feature, though).

Both are currently ignored and the USE flags are masked! So setting them will have no effect.

Assembly is unsupported upstream, they're working on an updated assembly workbench, as the current codebase is no longer compiling. For a discussion on this please see https://forum.freecadweb.org/viewtopic.php?f=4&t=39716

As for netgen support, I first need to check if this is working with latest releases. It has been difficult in the past and support on linux was temporarily removed upstream.

**Comment by CaptainBloodz** [comment]
> > Indeed. and {pyside2,pyside-tools2,shiboken2}-5.12.x.
> > assembly and netgen builded fine too (can't tell about stability or feature, though).
> 
> Nice! :) There's an upcoming patch for this, which checks for pyside2-tools or qtcore versions being installed and optionally applies the patch to use the generator option to rcc. So you will be able to use <qt-5.14 again.

I did'nt fall back to 5.12, I just didn't upgraded to 5.14
Are you saying  using {pyside2,pyside-tools2,shiboken2}-5.14.x likely to cause failure fail?

**Comment by waebbl** [comment]
> > > Indeed. and {pyside2,pyside-tools2,shiboken2}-5.12.x.
> > > assembly and netgen builded fine too (can't tell about stability or feature, though).
> > 
> > 
> > Nice! :) There's an upcoming patch for this, which checks for pyside2-tools or qtcore versions being installed and optionally applies the patch to use the generator option to rcc. So you will be able to use <qt-5.14 again.
> 
> I did'nt fall back to 5.12, I just didn't upgraded to 5.14
> Are you saying using {pyside2,pyside-tools2,shiboken2}-5.14.x likely to cause failure fail?

No the pyside2-5.14 don't cause any failure. I'm using them already for some time.
I don't mean you to fall back to 5.12. But for Qt 5.13 is the stable version and you were using 5.13, so I was assuming you are working with amd64 stable.
