### ISSUE TITLE
Main window size issue at bootsrap

### ISSUE THREAD

**Issue by CaptainBloodz** [waebbl/waebbl-gentoo#197]
Either 0.18.3 or 0.18.4 open main window slightly bigger than current screen.
This is annoying to access main menu bar, as it is partially obfuscated.

**Comment by waebbl** [comment]
This has nothing to do with the ebuild, and I can not fix this. Please file a bug upstream.

**Comment by CaptainBloodz** [comment]
Do you experience the same symptom?

**Comment by waebbl** [comment]
No, my window starts maximzed and fits into the screen. It might also be related to the window manager you're using. You can also check your monitor whether the size of the screen is correct. How it it, if you maximize the window of some other app, like a terminal or browser? Does it fit?

It's definitely not related to the ebuild. It does not set any window size related variables at compile time.

**Comment by CaptainBloodz** [comment]
LXDE + openbox here.
