### ISSUE TITLE
freecad-9999 wrong & hardcoded rcc/uic

### ISSUE THREAD

**Issue by Grawp** [waebbl/waebbl-gentoo#203]
These two recent lines
https://github.com/waebbl/waebbl-gentoo/blob/361e71c9bf46eeee396f742f5bfd9ca4175293c3/media-gfx/freecad/freecad-9999.ebuild#L234-L235
causes FreeCAD to fail at runtime when loading certain workbenches:
```
During initialization the error "invalid syntax (AddonManager_rc.py, line 1)" occurred in /usr/lib64/freecad/Mod/AddonManager/InitGui.py
Please look into the log file for further information
During initialization the error "invalid syntax (Tux_rc.py, line 1)" occurred in /usr/lib64/freecad/Mod/Tux/InitGui.py
Please look into the log file for further information
During initialization the error "invalid syntax (Draft_rc.py, line 1)" occurred in /usr/lib64/freecad/Mod/Draft/InitGui.py
Please look into the log file for further information
During initialization the error "invalid syntax (Arch_rc.py, line 1)" occurred in /usr/lib64/freecad/Mod/Arch/InitGui.py
Please look into the log file for further information
Unknown command 'Std_AddonMgr'
```
_/usr/bin/{rcc,uic}_ in my environment links to _qtchooser_ which may and in my case certainly does not lead to {uic,rcc} from *pyside2-tools* which causes certain resources not to build
```
*** Error compiling '/var/tmp/portage/media-gfx/freecad-9999/image/usr/lib64/freecad/Mod/AddonManager/AddonManager_rc.py'...
  File "/usr/lib64/freecad/Mod/AddonManager_rc.py", line 1
    /****************************************************************************
    ^
SyntaxError: invalid syntax
```

The building process should not implicitly depend on user's current environment.

After removing those two lines from the ebuild, PYSIDE2{RCC,UIC}BINARY get correctly resolved to {uic,rcc} from pyside2-tools and everything works then.

**Comment by waebbl** [comment]
Thanks @Grawp for pointing this out. I had a build failure once with the file AddonManager_rc.py, but it was not reproducible, so I decided to leave it alone for now.

> 
> _/usr/bin/{rcc,uic}_ in my environment links to _qtchooser_ which may and in my case certainly does not lead to {uic,rcc} from _pyside2-tools_ which causes certain resources not to build
> 

Py2side2-tools only install `{uic,rcc}` when build with `USE="tools"`, which in my opinion should normally not be done, as it will overwrite qtchooser from dev-qt/qtchooser.

> The building process should not implicitly depend on user's current environment.
> 
> After removing those two lines from the ebuild, PYSIDE2{RCC,UIC}BINARY get correctly resolved to {uic,rcc} from pyside2-tools and everything works then.

I will check this out.

**Comment by Grawp** [comment]
FYI after I removed those lines, cmake resolved the tools to
```
-- PySide2Tools:        [/usr/bin/pyside2-uic] [/usr/bin/pyside2-rcc]
```
which in my env belongs to *dev-python/pyside2-tools-5.12.5-r1* from **raiagent**'s repo which does not have the `tools` USE flag you mention.
```
 * Found these USE flags for dev-python/pyside2-tools-5.12.5-r1:
 U I
 + + python_targets_python2_7 : Build with Python 2.7
 + + python_targets_python3_6 : Build with Python 3.6
 - - python_targets_python3_7 : Build with Python 3.7
 - - test                     : Enable dependencies and/or preparations necessary to run tests (usually controlled by FEATURES=test but can be toggled
                                independently)
```

**Comment by waebbl** [comment]
So the problem seems to be related to 5.12 version of pyside2-tools. I'm using 5.14 which has the tools USE flag and also don't have the build time issue you're describing. But I didn't have the time yet to test about the runtime issue.
I will probably update the ebuild to use pyside2-tools-5.14 then.

**Comment by Grawp** [comment]
(Btw. just to be clear: The build time issue does not end the build. It builds successfully but then there's the runtime issue.)

It may be just that *pyside2-tools-5.14* requires newer *Qt* which brings newer *rcc* to which */usr/bin/rcc* defaults to via *qtchooser* and the newer *rcc* successfully builds the problematic .py resources.

**Comment by waebbl** [comment]
Ok, thank you. I will test and carefully check the output.

**Comment by waebbl** [comment]
@Grawp I just tested to build and install with my current (unchanged) configuration, which is qt-5.14 and pyside-5.14 and it built and installed succesfully. The `__pycache__` subdir for `Mod/AddonManager` in the sandbox install location contains compiled python scripts for the AddonManager_rc.py script.

I'm now updating to depend on pyside-5.14. AFAIK this pulls in qt-5.14 which then should work. I consider using the pyside-5.12 a little problematic as the qt-5.12 packages are already masked in Gentoo tree, so the reason could also be some incompatibilities between qt-5.{13,14} and pyside-5.12.

If you like, I'd be happy if you could test on the PR I'm going to push and give me feedback, whether it the issue persists or not.
