### ISSUE TITLE
gentoo: git-python moved to GitPython

### ISSUE THREAD

**Issue by CaptainBloodz** [waebbl/waebbl-gentoo#206]
Patched ebuild

[freecad-0.18.4-r11.ebuild.zip](https://github.com/waebbl/waebbl-gentoo/files/4330546/freecad-0.18.4-r11.ebuild.zip)

Should work, couldn't test for full build because netgen issue somehow.
Dependency seems properly resolved though.

Thks 4 ur attention, interest & support.

**Comment by waebbl** [comment]
Thank @CaptainBloodz, just synced an hour ago and noticed this. Need to update first, before the change gets applied.

**Comment by CaptainBloodz** [comment]
Above patched ebuild tested working.
Thks 4 ur attention, interest & support.
