### ISSUE TITLE
media-gfx/freecad-)0.18.4-r1: failed to build with netgen-6.2.1910

### ISSUE THREAD

**Issue by CaptainBloodz** [waebbl/waebbl-gentoo#207]
[media-gfx:freecad-0.18.4-r11:20200313-201506.log](https://github.com/waebbl/waebbl-gentoo/files/4331936/media-gfx.freecad-0.18.4-r11.20200313-201506.log)

builds fine with netgen-6.2.1810

Thks 4 ur attention, interest & support.

**Comment by waebbl** [comment]
How did you manage to go around the masked netgen USE flag? The masking has a purpose.

**Comment by CaptainBloodz** [comment]
I don't think I did anything for that.

**Comment by waebbl** [comment]
Could you please double-check that your profiles/package.use.mask looks like https://github.com/waebbl/waebbl-gentoo/blob/master/profiles/package.use.mask? Especially that the last line is present? If it's not, please sync your local repo from master and check you don't overwrite this file with any local changes afterwards.

**Comment by CaptainBloodz** [comment]
Local file content matches pointed url above.
Still, netgen isn't masked.

eix freecad
[I] media-gfx/freecad
     Available versions:  ~0.18.3[2] ~0.18.3-r1[2] (~)0.18.4-r1[1] (~)0.18.4-r11[2] ~0.18.4-r12[2] (~)0.18.4-r111[2] **9999*l[1] **9999*l[2] {+addonmgr +arch -assembly +complete debug doc +drawing +fem +idf +image +inspection +material +mesh mpi netgen +openscad +part_design +path pcl -plot +points +raytracing +reverseengineering +robot +-ship +show +spreadsheet +surface +techdraw +tux PYTHON_SINGLE_TARGET="+python3_6"}
     Installed versions:  0.18.4-r11[2](12:50:33 15/03/2020)(addonmgr arch assembly doc drawing fem idf image inspection material mesh mpi netgen openscad part_design path pcl points raytracing robot show spreadsheet surface techdraw tux -debug -plot -ship PYTHON_SINGLE_TARGET="python3_6")
     Homepage:            https://www.freecadweb.org/
     Description:         QT based Computer Aided Design application

[1] "waebbl" /var/db/repos/waebbl
[2] "local-repo" /var/db/repos/local-repo

Found 2 matches
amd64 ~ # equery u media-gfx/freecad-0.18.4-r1
USE flags should not start with a '+': +arch
USE flags should not start with a '+': +fem
USE flags should not start with a '+': +inspection
USE flags should not start with a '+': +mesh
USE flags should not start with a '+': +openscad
[ Legend : U - final flag setting for installation]
[        : I - package is installed with flag     ]
[ Colors : set, unset                             ]
 * Found these USE flags for media-gfx/freecad-0.18.4-r1:
 U I
 + - addonmgr                       : Build the addon manager module for automatic
                                      handling of 3rd party addons 
 + - arch                           : Build the architecture workbench for working
                                      with architectural elements 
 + - assembly                       : Build the assembly module 
 - - debug                          : Enable extra debug codepaths, like asserts and
                                      extra output. If you want to get meaningful
                                      backtraces see https://wiki.gentoo.org/wiki/Pr
                                      oject:Quality_Assurance/Backtraces
 + - doc                            : Add extra documentation (API, Javadoc, etc).
                                      It is recommended to enable per package
                                      instead of globally
 + - drawing                        : Build the drawing module and workbench to
                                      display 3D work on a 2D sheet 
 + - fem                            : Build the FEM module and workbench which
                                      provides Finite Element Analysis (FEA)
                                      workflows 
 + - idf                            : Build the IDF module to provide file exchange
                                      capabilities with IDF files 
 + - image                          : Build the image module and workbench for
                                      working with bitmap images 
 + - inspection                     : Build the inspection workbench which gives you
                                      specific tools for examination of shapes
                                      (experimental) 
 + - material                       : Build the material module and workbench to
                                      work with materials 
 + - mesh                           : Build the mesh module and workbench to work
                                      with triangulated meshes 
 + - mpi                            : Add MPI (Message Passing Interface) layer to
                                      the apps that support it
 + - netgen                         : Support sci-mathematics/netgen with the FEM
                                      workbench 
 + - openscad                       : Build the OpenSCAD module for interoperability
                                      with OpenSCAD and repairing Constructive Solid
                                      Geometry (CSG) history 
 + - part_design                    : Build the part design module and workbench for
                                      build part shapes from sketches 
 + - path                           : Build the path module and workbench to procude
                                      G-Code instructions for CNC 
 + - pcl                            : Use external sci-libs/pcl for point clouds
                                      support. 
 - - plot                           : Build the internal plot workbench. NOTE: This
                                      conflicts with the external plot workbench,
                                      which you can add via the Addon Manager! 
 + - points                         : Build the points module and workbench for
                                      working with point clouds 
 + + python_single_target_python3_6 : Build for Python 3.6 only
 + - raytracing                     : Build the raytracing module and workbench for
                                      raytracing and rendering 
 + - robot                          : Build the robot module and workbench for
                                      studying robot movements 
 - - ship                           : Build the ship module and workbench which
                                      works over ship entities, that must be created
                                      on top of provided geometry. NOTE: This
                                      conflicts with the external ship workbench,
                                      which you can add via the Addon Manager! 
 + - show                           : Build the show module, a helper module for
                                      visibility automation 
 + - spreadsheet                    : Build the spreadsheet module and workbench to
                                      create and manipulate spreadsheet data 
 + - surface                        : Build the surface module and workbench 
 + - techdraw                       : Build the techdraw module and workbench, a
                                      more advanced and feature-rich successor of
                                      the drawing workbench 
 + - tux                            : Build the Tux module 
amd64 ~ # grep -r netgen /etc/portage
/etc/portage/package.use/10-stage4-netgen-monolithic.conf:sci-mathematics/netgen python
/etc/portage/package.use/10-stage4-netgen-monolithic.conf:sci-mathematics/netgen python_single_target_python3_6
/etc/portage/package.use/10-stage4-netgen-monolithic.conf:sci-mathematics/netgen opencascade
/etc/portage/package.use/10-stage4-netgen-monolithic.conf:sci-mathematics/netgen mpi
/etc/portage/package.use/04-stage4-freecad-monolithic.conf:media-gfx/freecad netgen
/etc/portage/package.mask/monolithic.conf:=sci-mathematics/netgen-6.2.1910
/etc/portage/package.accept_keywords/10-stage4-netgen-monolithic.conf:=sci-mathematics/netgen-6.2.1810 ~amd64
/etc/portage/package.accept_keywords/10-stage4-netgen-monolithic.conf:=sci-mathematics/netgen-6.2.1810-r1 ~amd64
/etc/portage/package.accept_keywords/10-stage4-netgen-monolithic.conf:=sci-mathematics/netgen-6.2.1910 ~amd64

**Comment by CaptainBloodz** [comment]
> How did you manage to go around the masked netgen USE flag? The masking has a purpose.

I just moved ebuild to local repository.

Thks 4 ur attention, interest & support

**Comment by waebbl** [comment]
Then you are on your own. Like I said above, the mask is there for a reason. If you undergo the mask, you need to be able to fix the issues coming up from this. Only break the rules, if you can live with it.
Closing this.
