### ISSUE TITLE
sci-libs/vtk-8.2.0-r1: add python3_7 to PYTHON_COMPAT

### ISSUE THREAD

**Issue by Fat-Zer** [waebbl/waebbl-gentoo#213]
Some time ago you removed `python3_7` from `PYTHON_COMPAT` on the sad ebuild. Could you please readd it, because as for now python-3.7  is stable and the ebuild compiles fine with it...

**Comment by waebbl** [comment]
It alos compiled fine when I removed it. The removal was due to dependencies of vtk not having py3.7 support. I'm going to check whether this is now working.

**Comment by Fat-Zer** [comment]
Should be fine... python deps aren't any different from gentoo's upstream and upstream got python3_7 enabled on a stable version ;)

PS: there is a couple additional USE's and some other changes on the portage tree's ebuild that you might want to port...

**Comment by waebbl** [comment]
> Should be fine... python deps aren't any different from gentoo's upstream and upstream got python3_7 enabled on a stable version ;)
> 
Who do you mean with upstream? Kitware? 
On Gentoo tree, we have currently version 8.1.0, while I have 8.2.0. Even if the python deps might not be quite different, at the time I removed py3.7 support, I got a whole lot of fatal repoman errors due to packages not having py3.7 support. It might have changed with recent commits to python packages though.

> PS: there is a couple additional USE's and some other changes on the portage tree's ebuild that you might want to port...

The two flags which are missing, tcl and tk are no longer supported with 8.2.0.

**Comment by Fat-Zer** [comment]
> Who do you mean with upstream? Kitware?
gentoo tree

> On Gentoo tree, we have currently version 8.1.0, while I have 8.2.0. Even if the python deps might not be quite different, at the time I removed py3.7 support, I got a whole lot of fatal repoman errors due to packages not having py3.7 support.

yeah... AFAIR there were a lot of troubles at the time of unmasking python3_7-related USE's and stabilization of the python package all over the tree a month or so ago (even layman got some dependencies missing)... but almost all those were wiped away pretty quickly... likely, you just chose a bad time to check it ;)...

>The two flags which are missing, tcl and tk are no longer supported with 8.2.0.

Oh... sorry for bothering with that...

**Comment by waebbl** [comment]
There are still two dependencies, `dev-python/autobahn` and `dev-python/txaio` which don't have python 3.7 support and therefore give fatal errors with repoman and will likely give build failures too.

**Comment by Fat-Zer** [comment]
@waebbl yeah, you are right, although those won't cause build failures as far as they are `RDEPEND`'s for `USE=web`, but they will almost positively make web app unusable...  sorry for bothering with the issue, feel free to close it...

PS: It's very embracing, but I was also wrong about gentoo portage tree's version of `sci-libs/vtk`... it doesn't have any support for python-3.7 yet... I don't know why and with what I could confuse it with something else...

**Comment by waebbl** [comment]
@Fat-Zer I'm closing this for now, but will try to keep an eye on updates for python 3.7.
Feel free to re-open it, if you find the packages have been updated and I don't react in time.

**Comment by Fat-Zer** [comment]
=dev-python/autobahn-20.4.3 has the python3_7 support now, so you might want to test if vtk builds fine with USE=web and finally add the python3_7 to PYTHON_COMPAT... Also you might want to test if it got everything it needs for python3_8 support...
