### ISSUE TITLE
Can't configure media-gfx/freecad-9999

### ISSUE THREAD

**Issue by ElDavoo** [waebbl/waebbl-gentoo#214]
CMake Error at cMake/FreeCAD_Helpers/SetupPybind11.cmake:7 (find_package):
  By not providing "Findpybind11.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "pybind11",
  but CMake did not find one.

  Could not find a package configuration file provided by "pybind11" with any
  of the following names:

    pybind11Config.cmake
    pybind11-config.cmake

  Add the installation prefix of "pybind11" to CMAKE_PREFIX_PATH or set
  "pybind11_DIR" to a directory containing one of the above files.  If
  "pybind11" provides a separate development package or SDK, be sure it has
  been installed.
Call Stack (most recent call first):
  CMakeLists.txt:54 (SetupPybind11)

However, pybind11 is installed.

Portage 2.3.94 (python 3.8.2-final-0, default/linux/amd64/17.1/desktop, gcc-9.3.0, glibc-2.30-r6, 5.5.10-gentoo x86_64)
=================================================================
                         System Settings
=================================================================
System uname: Linux-5.5.10-gentoo-x86_64-Intel-R-_Pentium-R-_CPU_N3520_@_2.16GHz-with-glibc2.2.5
KiB Mem:     3910332 total,    893032 free
KiB Swap:    4095996 total,   3896828 free
Timestamp of repository gentoo: Sat, 21 Mar 2020 09:38:32 +0000
Head commit of repository gentoo: c74cd0713aa8c5798242381c6269045e0a141f94

sh bash 5.0_p16
ld GNU ld (Gentoo 2.34 p1) 2.34.0
ccache version 3.7.8 [enabled]
app-shells/bash:          5.0_p16::gentoo
dev-java/java-config:     2.2.0-r4::gentoo
dev-lang/perl:            5.30.1::gentoo
dev-lang/python:          2.7.17-r100::lto-overlay, 3.6.10-r1::lto-overlay, 3.7.7::gentoo, 3.8.2::gentoo
dev-util/ccache:          3.7.8::gentoo
dev-util/cmake:           3.17.0::gentoo
dev-util/pkgconfig:       0.29.2::gentoo
sys-apps/baselayout:      2.7::gentoo
sys-apps/openrc:          0.42.1::gentoo
sys-apps/sandbox:         2.18::gentoo
sys-devel/autoconf:       2.13-r1::gentoo, 2.69-r5::gentoo
sys-devel/automake:       1.16.1-r2::gentoo
sys-devel/binutils:       2.34::gentoo
sys-devel/gcc:            9.3.0::gentoo
sys-devel/gcc-config:     2.2.1::gentoo
sys-devel/libtool:        2.4.6-r6::gentoo
sys-devel/make:           4.3::gentoo
sys-kernel/linux-headers: 5.5::gentoo (virtual/os-headers)
sys-libs/glibc:           2.30-r6::gentoo
Repositories:

crossdev
    location: /usr/local/portage-crossdev
    masters: gentoo
    priority: 10

bombo82
    location: /var/lib/layman/bombo82
    masters: gentoo
    priority: 50

eclipse
    location: /var/lib/layman/eclipse
    masters: gentoo
    priority: 50

jollheef-overlay
    location: /var/lib/layman/jollheef-overlay
    masters: gentoo
    priority: 50

jorgicio
    location: /var/lib/layman/jorgicio
    masters: gentoo
    priority: 50

linxon
    location: /var/lib/layman/linxon
    masters: gentoo
    priority: 50

lto-overlay
    location: /var/lib/layman/lto-overlay
    masters: gentoo mv
    priority: 50

mv
    location: /var/lib/layman/mv
    masters: gentoo
    priority: 50

pentoo
    location: /var/lib/layman/pentoo
    masters: gentoo
    priority: 50

raiagent
    location: /var/lib/layman/raiagent
    masters: gentoo
    priority: 50

soltys
    location: /var/lib/layman/soltys
    masters: gentoo
    priority: 50

steam-overlay
    location: /var/lib/layman/steam-overlay
    masters: gentoo
    priority: 50

tastytea
    location: /var/lib/layman/tastytea
    masters: gentoo
    priority: 50

waebbl
    location: /var/lib/layman/waebbl
    masters: gentoo raiagent
    priority: 50

gentoo
    location: /usr/portage
    sync-type: git
    sync-uri: https://github.com/gentoo-mirror/gentoo.git
    priority: 1000

ACCEPT_KEYWORDS="amd64 ~amd64"
ACCEPT_LICENSE="*"
CBUILD="x86_64-pc-linux-gnu"
CFLAGS="-O2 -fno-stack-protector -fno-stack-check -fomit-frame-pointer -march=native -mtune=native -falign-functions=32 -O2 -pipe"
CHOST="x86_64-pc-linux-gnu"
CONFIG_PROTECT="/etc /usr/share/gnupg/qualified.txt"
CONFIG_PROTECT_MASK="/etc/ca-certificates.conf /etc/dconf /etc/env.d /etc/fonts/fonts.conf /etc/gconf /etc/gentoo-release /etc/revdep-rebuild /etc/sandbox.d /etc/terminfo"
CXXFLAGS="-O2 -fno-stack-protector -fno-stack-check -fomit-frame-pointer -march=native -mtune=native -falign-functions=32 -O2 -pipe"
DISTDIR="/usr/portage/distfiles"
ENV_UNSET="DBUS_SESSION_BUS_ADDRESS DISPLAY GOBIN PERL5LIB PERL5OPT PERLPREFIX PERL_CORE PERL_MB_OPT PERL_MM_OPT XAUTHORITY XDG_CACHE_HOME XDG_CONFIG_HOME XDG_DATA_HOME XDG_RUNTIME_DIR"
FCFLAGS="-O2 -pipe"
FEATURES="assume-digests binpkg-docompress binpkg-dostrip binpkg-logs ccache config-protect-if-modified distlocks ebuild-locks fixlafiles ipc-sandbox merge-sync multilib-strict network-sandbox news parallel-fetch parallel-install pid-sandbox preserve-libs protect-owned qa-unresolved-soname-deps sandbox sfperms strict unknown-features-warn unmerge-logs unmerge-orphans userfetch userpriv usersandbox usersync xattr"
FFLAGS="-O2 -pipe"
GENTOO_MIRRORS="http://mirror.eu.oneandone.net/linux/distributions/gentoo/gentoo/ http://gentoo.mirrors.ovh.net/gentoo-distfiles/ ftp://gentoo.mirrors.ovh.net/gentoo-distfiles/ rsync://mirror.eu.oneandone.net/gentoo/"
LANG="it_IT.utf8"
LDFLAGS="-Wl,-O1 -Wl,--as-needed"
LINGUAS="it"
MAKEOPTS="-j4 -l5"
PKGDIR="/usr/portage/packages"
PORTAGE_CONFIGROOT="/"
PORTAGE_RSYNC_OPTS="--recursive --links --safe-links --perms --times --omit-dir-times --compress --force --whole-file --delete --stats --human-readable --timeout=180 --exclude=/distfiles --exclude=/local --exclude=/packages --exclude=/.git"
PORTAGE_TMPDIR="/var/tmp"
USE="X \ a52 aac acl acpi alsa amd64 berkdb bluetooth branding btrfs bzip2 cairo cdda cdr chromium cli crypt cups custom-cflags custom-optimization dbus default-gold dhcpcd dos dri dts dvdr elogind emboss encode exif fat ffmpeg flac fortran gdbm gecko gif glamor gpm graphite gtk gtk3 hangouts hostonly hpn iconv icu ipv6 jbr11 jpeg lcms ldap libnotify libtirpc mad mng modern-top mono mp3 mp4 mpeg mtp multilib native-headset ncurses nfc nls nptl nptlonly ntfs ocl-icd ofono-headset ogg opencl opengl openmp openssl opus override-flagomatic pam pango pcap pcre pcsc-lite pdf pgo pipelight pm-utils png policykit ppds prelink proprietary-codecs pulseaudio qt5 rar readline realtime run-exes samba sdl seccomp spell spice split-usr ssd ssl startup-notification subversion svg symlink system-bootstrap system-ffmpeg system-harfbuzz system-icu system-jpeg system-libevent system-libvpx system-llvm system-sqlite systray tcpd threads tiff tk truetype udev udisks unicode unicorn_targets_x86 upower usb v4l vaapi virgl vkd3d vorbis vulkan widevine wifi winbind wxwidgets x264 x265 xattr xcb xfce xml xv xvid zlib" ABI_X86="64" ADA_TARGET="gnat_2018" ALSA_CARDS="ali5451 als4000 atiixp atiixp-modem bt87x ca0106 cmipci emu10k1x ens1370 ens1371 es1938 es1968 fm801 hda-intel intel8x0 intel8x0m maestro3 trident usb-audio via82xx via82xx-modem ymfpci" APACHE2_MODULES="authn_core authz_core socache_shmcb unixd actions alias auth_basic authn_alias authn_anon authn_dbm authn_default authn_file authz_dbm authz_default authz_groupfile authz_host authz_owner authz_user autoindex cache cgi cgid dav dav_fs dav_lock deflate dir disk_cache env expires ext_filter file_cache filter headers include info log_config logio mem_cache mime mime_magic negotiation rewrite setenvif speling status unique_id userdir usertrack vhost_alias" CALLIGRA_FEATURES="karbon sheets words" COLLECTD_PLUGINS="df interface irq load memory rrdtool swap syslog" CPU_FLAGS_X86="mmx mmxext pclmul popcnt sse sse2 sse3 sse4_1 sse4_2 ssse3" ELIBC="glibc" GPSD_PROTOCOLS="ashtech aivdm earthmate evermore fv18 garmin garmintxt gpsclock greis isync itrax mtk3301 nmea ntrip navcom oceanserver oldstyle oncore rtcm104v2 rtcm104v3 sirf skytraq superstar2 timing tsip tripmate tnt ublox ubx" INPUT_DEVICES="synaptics libinput keyboard mouse" KERNEL="linux" L10N="it" LCD_DEVICES="bayrad cfontz cfontz633 glk hd44780 lb216 lcdm001 mtxorb ncurses text" LIBREOFFICE_EXTENSIONS="presenter-console presenter-minimizer" LLVM_TARGETS="X86 Aarch64" OFFICE_IMPLEMENTATION="libreoffice" PHP_TARGETS="php7-2" POSTGRES_TARGETS="postgres10 postgres11" PYTHON_SINGLE_TARGET="python3_7" PYTHON_TARGETS="python3_7 python3_8" QEMU_SOFTMMU_TARGETS="x86_64" QEMU_USER_TARGETS="x86_64" RUBY_TARGETS="ruby27" USERLAND="GNU" VIDEO_CARDS="intel i965" XTABLES_ADDONS="quota2 psd pknock lscan length2 ipv4options ipset ipp2p iface geoip fuzzy condition tee tarpit sysrq steal rawnat logmark ipmark dhcpmac delude chaos account"
Unset:  CC, CPPFLAGS, CTARGET, CXX, EMERGE_DEFAULT_OPTS, INSTALL_MASK, LC_ALL, PORTAGE_BINHOST, PORTAGE_BUNZIP2_COMMAND, PORTAGE_COMPRESS, PORTAGE_COMPRESS_FLAGS, PORTAGE_RSYNC_EXTRA_OPTS

=================================================================
                        Package Settings
=================================================================

dev-python/pybind11-2.4.3::gentoo was built with the following:
USE="" ABI_X86="(64)" PYTHON_TARGETS="python3_6 python3_7 python3_8"
CFLAGS="-O2 -fno-stack-protector -fno-stack-check -fomit-frame-pointer -march=native -mtune=native -falign-functions=32 -O2 -pipe -Wl,-O1 -Wl,--as-needed"
CXXFLAGS="-O2 -fno-stack-protector -fno-stack-check -fomit-frame-pointer -march=native -mtune=native -falign-functions=32 -O2 -pipe -Wl,-O1 -Wl,--as-needed"

**Comment by waebbl** [comment]
You need to install the pybind11 from my overlay, which installs the needed cmake files. 
See https://bugs.gentoo.org/706070

**Comment by ElDavoo** [comment]
Ok thanks, that worked. Is there any way to know every ::gentoo ebuild that
needs to be masked or is it try and experiment?

Il sab 21 mar 2020, 11:16 Bernd <notifications@github.com> ha scritto:

**Comment by waebbl** [comment]
None that I know of, it's trial and error. I've tried adding the repository name to dependency strings, but it didn't work out.
