### ISSUE TITLE
media-gfx/freecad cannot build against sci-libs/opencascade-7.4.0-r1

### ISSUE THREAD

**Issue by hedmo** [waebbl/waebbl-gentoo#227]
media-gfx/freecad cannot build against sci-libs/opencascade-7.4.0-r1

[build.log](https://github.com/waebbl/waebbl-gentoo/files/4540312/build.log)

media-gfx/freecad cannot build against sci-libs/opencascade-7.4.0-r1 because it is looking 
for files in /usr/lib64/opencascade-7.4.0 but the files are in /usr/lib64/opencascade-7.4.0-r1
and if i make a symlink : 
`ln -s  /usr/lib64/opencascade-7.4.0-r1 /usr/lib64/opencascade-7.4.0`

it works

regards hedmo

**Comment by hedmo** [comment]
fixed via:
https://github.com/gentoo/gentoo/commit/0c80e6025a81328f5d4efaf95bcc1b805c9dad51

**Comment by waebbl** [comment]
Oh wow, that was a quick fix :D 
Thanks @tamiko

**Comment by tamiko** [comment]
:smile_cat:
