### ISSUE TITLE
media-gfx/freecad opencascade libdir handling fails

### ISSUE THREAD

**Issue by lorem-ipsum** [waebbl/waebbl-gentoo#228]
The freecad ebuild has extra handling for the latest opencascade version, but it only checks for `=sci-libs/opencascade-7.4.0:7.4.0` which no longer matches the sci-libs/opencascade-7.4.0-r2 in the main tree. Changing it to `~sci-libs/opencascade-7.4.0:7.4.0` fixes it for now, but as this is the only version of opencascade existing in the main tree it might be easier to just apply the libdir fix unconditionally.

**Comment by CaptainBloodz** [comment]
alternatively:
    local occ_lib="lib"
    if has_version "=sci-libs/opencascade-7.3.0:7.3.0"; then
       occ_lib=$(get_libdir)
    fi

or fail back
       -DOCC_LIBRARY_DIR="${CASROOT}/${occ_lib}"

to
       -DOCC_LIBRARY_DIR="${CASROOT}"/$(get_libdir)

Thks 4 ur attention, interest & support.
