### ISSUE TITLE
Opencollada version bump

### ISSUE THREAD

**Issue by redchillipadi** [waebbl/waebbl-gentoo#231]
I have cleaned up the opencollada ebuild a bit in my repository and fixed some QA issues regarding DAEValidator and its library. We need version 1.6.68 in the tree as it is a dependency for blender. I was planning to write a PR for it if you don't mind, most of the initial work was based on your ebuild.

**Comment by waebbl** [comment]
Go ahead, I'm fine with it.

**Comment by redchillipadi** [comment]
Thanks, I have submitted it, but might not get much attention until there is a maintainer. I will try to get it pushed through when I submit blender.

https://bugs.gentoo.org/721682

**Comment by waebbl** [comment]
Ok fine! I noticed you added yourself as a proxy maintainer, so there are chances it's getting pushed.
