### ISSUE TITLE
irc pm

### ISSUE THREAD

**Issue by ZeroChaos-** [waebbl/waebbl-gentoo#240]
Hi.  Someone with your nick appeared on irc to admonish me via pm, and then disappeared before response.  So just in case it was you, I'm leaving a response here.

Message for context
```
01:58 <waebbl> ?OTR,00001,00002,Hi, I'm not happy how you treated me with regards to the pybind11 ebuild. I had a PR for this open since March, updated it regularly to resolve conflicts and 
               updated it to 2.5.0 when it came out. Yet instead of just merging this PR, you updated the ebuild on your behalf, by picking up my ebuild, yet not mentioning my work in the 
               commit message. This is known as stealing in coutry. You surely kno,
01:58 <waebbl> ?OTR,00002,00002,w there are tags for things such as closing a bug, mentioning someones work, etc. But you seem not be capable of using those techniques. I will keep this 
               behaviour in mind and take my time to think about possible actions I will take from it. I  IIII I I I    II  I   II  II,
```

First of all, I apologize for the confusion, but I literally didn't even look for a PR when I was working on this.  That's my bad, and it sounds like it would have saved me some work, but I didn't see your PR.  I'm not positive I saw your overlay (although based on after the fact investigation I'm pretty certain I did), as I was working with noc0lour based on his work, which was entirely different from both the ebuild in your tree right now, and the ebuild I committed.

I did see the ebuild in your tree, and part of my work was based on that, but as you can see, my ebuild is different.  My intent wasn't to rip you off, or steal your work, I merged work from multiple sources to make something that worked properly and then I committed it.  I should have cited inspirational sources such as you, but I did *not* simply steal your work and commit it as my own, nor would I ever do such a thing intentionally.

Again, I apologize for the confusion, and I also apologize for not citing you as inspirational in the ebuild I commited.  That said, I didn't simply take your work and claim it as my own, and even after the fact I can't find a PR for pybind11-2.5.0 nor one that matches the ebuild I committed.  I can't honestly remember how many sources I looked at while writing the ebuild and trying to fix it up from what was so obviously broken in gentoo, but it's pretty obvious to me that I based much  of the work on your ebuild, but that mine is not an exact copy of yours.  Given these facts, is there something I can do at this point to make it right?  Would you like to be listed as a maintainer?  Or should I add to the metadata description that your work inspired me?  I could add your name in the ebuild if you like.  Is there any way to properly record that your work inspired mine?

**Comment by waebbl** [comment]
solved in IRC
