### ISSUE TITLE
backport patch of vtk to let it compile with gcc 10

### ISSUE THREAD

**Issue by ElDavoo** [waebbl/waebbl-gentoo#243]
**Describe the bug**
vtk doesn't compile

**Please always add the following information (attach them or provide a link where they can be found). Bug reports without these information are considered invalid and will be closed:**
 https://bugs.gentoo.org/723374

**Additional context**
https://gitweb.gentoo.org/repo/gentoo.git/commit/?id=64839f71f4892ca57ce5e36648b9a2b1c8a60822

**Comment by waebbl** [comment]
Thanks for the report. I'm gonna backport the patch.
