### ISSUE TITLE
Remove ebuild patch

### ISSUE THREAD

**Issue by RayOfLight1** [waebbl/waebbl-gentoo#244]
https://github.com/waebbl/waebbl-gentoo/blob/570e51997adb422577353915f95135c03a519cd6/media-gfx/freecad/freecad-9999.ebuild#L152

Hello, afaik, the " "${FILESDIR}/${PN}-0.18.4-0006-add-missing-include-statements.patch" patch is not needed anymore, and if you keep the line in, the patching fails and thus the merge preparation.

Regards,

**Comment by waebbl** [comment]
Thanks for reporting this. I'm gonna fix it.

**Comment by waebbl** [comment]
@RayOfLight1 The issue should have been resolved with the last update of the live ebuild.
If the problem persists, feel free to re-open the issue.
