### ISSUE TITLE
media-gfx/freecad-0.18.4-r1::waebbl failed to emerge: Could not find a package configuration file provided by "pybind11" 

### ISSUE THREAD

**Issue by thinrope** [waebbl/waebbl-gentoo#245]
Just started testing this package... all deps were emerged with no much issues, but `freecad-0.18.4-r1` failed
````
$ sudo emerge media-gfx/freecad -vt
[ebuild  N    ~] media-gfx/freecad-0.18.4-r1::waebbl  USE="addonmgr arch drawing fem idf image inspection material mesh openscad part-design path points raytracing robot show spreadsheet surface techdraw tux (-assembly) -debug -doc -mpi (-netgen) -pcl -plot -ship" PYTHON_SINGLE_TARGET="python3_7 -python3_6" 0 KiB
...
>>> Emerging (1 of 1) media-gfx/freecad-0.18.4-r1::waebbl
...
-- Found PythonInterp: /tmp/portage/media-gfx/freecad-0.18.4-r1/temp/python3.7/bin/python (found version "3.7.8") 
-- Found PythonLibs: /usr/lib64/libpython3.7m.so (found suitable exact version "3.7.8") 
CMake Error at CMakeLists.txt:585 (find_package):
  By not providing "Findpybind11.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "pybind11",
  but CMake did not find one.

  Could not find a package configuration file provided by "pybind11" with any
  of the following names:

    pybind11Config.cmake
    pybind11-config.cmake

  Add the installation prefix of "pybind11" to CMAKE_PREFIX_PATH or set
  "pybind11_DIR" to a directory containing one of the above files.  If
  "pybind11" provides a separate development package or SDK, be sure it has
  been installed.
...
````
After some debugging I realized that your overlay also provides pybind11 ebuild, so I unmasked and now it builds OK.

I compared the two ebuilds (vanilla and yours) and they are quite different! Do you think we should bugger gentoo to fix the ebuild in the tree? I see that the vanilla pybind11 does not install `/usr/share/cmake/pybind11` and there is no useflag or other way to do it, which qualifies as a bug IMHO.

**Comment by waebbl** [comment]
Hi, the cmake issue with pybind11 should have been fixed with the 2.5.0 release. Could it be, you have an earlier version installed? The one from my overlay is outdated (being 2.4.3). I have 2.5.0 from ::gentoo installed here and it does install the cmake files. 
This issue should have been fixed with the bump to 2.5.0.

**Comment by thinrope** [comment]
Yes, in an attempt to have as few ~arch packages as possible, I ended with `=dev-python/pybind11-2.4.3::gentoo` and it doesn't work.
I tested with `=dev-python/pybind11-2.4.3::waebbl` and all works fine.
I just re-emerged with another set of settings and `=dev-python/pybind11-2.5.0::gentoo` and all is fine too.

You can probably close this bug as is, since we have no easy control over removing `=dev-python/pybind11-2.4.3::gentoo` and it will likely soon be gone once 2.5.0 is stabilized.

**Comment by waebbl** [comment]
@thinrope Please try again with freecad-0.18.5. I've had no issues building it again pybind11-2.6.1::gentoo.
Feel free to re-open if the issue persists.
