### ISSUE TITLE
update to xerces-c-3.2.3: "could not open catalog"

### ISSUE THREAD

**Issue by zmuser** [waebbl/waebbl-gentoo#247]
upgrading from xerces-c 3.2.2-r1 to 3.2.3 breaks the path /usr/share/xerces-c/msg/XercesMessages_en_US.cat.
rolling back solves the problem here.
See https://forum.freecadweb.org/viewtopic.php?f=4&t=49674
Thanks!

**Comment by zmuser** [comment]
Which freecad version do you have?
OS: Gentoo/Linux
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 0.18.Unknown
Build type: Release
Python version: 3.7.8
Qt version: 5.14.2
Coin version: 4.0.0
OCC version: 7.4.0
Locale: C/Default (C)

> Have you tried to run emerge with `--deep --newuse` beforehand?
yes
> Have you tried re-building freecad after upgrading xerces-c?
yes
> Could you please try to produce a log for freecad (run `freecad --write-log`) and post the created `~/.FreeCAD/FreeCAD.log` here?
(from my working environment)
Log: Time = Sun Aug 23 18:38:52 2020
Log: AppDataSkipVendor = true
Log: AppHomePath = /usr/lib64/freecad/
Log: AppIcon = freecad
Log: AppTempPath = /tmp/
Log: BinPath = /usr/lib64/freecad/bin/
Log: BuildRepositoryURL = Unknown
Log: BuildRevision = Unknown
Log: BuildRevisionDate = Unknown
Log: BuildVersionMajor = 0
Log: BuildVersionMinor = 18
Log: CSF_GraphicShr = /usr/lib64/opencascade-7.4.0/ros/lib64/libTKOpenGl.so
Log: CSF_IGESDefaults = /usr/lib64/opencascade-7.4.0/ros/share/opencascade/resources/XSTEPResource
Log: CSF_MDTVTexturesDirectory = /usr/lib64/opencascade-7.4.0/ros/share/opencascade/resources/Textures
Log: CSF_PluginDefaults = /usr/lib64/opencascade-7.4.0/ros/share/opencascade/resources/StdResource
Log: CSF_SHMessage = /usr/lib64/opencascade-7.4.0/ros/share/opencascade/resources/SHMessage
Log: CSF_STEPDefaults = /usr/lib64/opencascade-7.4.0/ros/share/opencascade/resources/XSTEPResource
Log: CSF_StandardDefaults = /usr/lib64/opencascade-7.4.0/ros/share/opencascade/resources/StdResource
Log: CSF_UnitsDefinition = /usr/lib64/opencascade-7.3.0/ros/share/opencascade/resources/UnitsAPI/Units.dat
Log: CSF_XCAFDefaults = /usr/lib64/opencascade-7.4.0/ros/share/opencascade/resources/StdResource
Log: Console = 0
> 
> I have xerces-c-3.2.3 installed here and don't see the issue.
I can try later to install again the 3.2.3 and see if the issue is back. 
> 
> Thanks for your help!

**Comment by waebbl** [comment]
I didn't have the issue when updating from 3.2.2-r1 to 3.2.3. This happened on 19th of July, while my freecad was last built on 8th of June, so I didn't even have to rebuild it.
Also, I don't have the `/usr/msg/` path which you're talking of in the freecad forum post. This isn't a FHS compliant path either, which means the xerces-c ebuild has an issue.

Running a few test builds in a chroot, I noticed this might be tied to USE flags `iconv` and `icu`. If I use `USE=iconv -icu` the ebuild installs an environment into `/etc/env.d/50xerces-c` which contains the path the NLS message catalog file and defaults to `/usr/share/xerces-c/msg`, but it wrongly installs the catalog file into `/usr/msg`. 3.2.2-r1 installs it into the correct directory.

Searching b.g.o, I noticed the issue has already been reported, see https://bugs.gentoo.org/738140

Please watch this bug on b.g.o. and report further issues there. It looks, like this is not tied to freecad at all. 

Some ways to solve it, are changing the variable inside the environment file, so it points to `/usr/msg`, moving the file in `/usr/msg` to `/usr/share/xerces-c/msg` should also work. Additionally you can `USE=icu` which removes the need for NLS message catalogs.

**Comment by waebbl** [comment]
Closing this. Feel free to re-open if the issue persists.

**Comment by zmuser** [comment]
my bad..I modified the USE flags according with your msg, all OK. Thanks!!
