### ISSUE TITLE
FreeCAD-9999 build error with USE="netgen"

### ISSUE THREAD

**Issue by brothermechanic** [waebbl/waebbl-gentoo#249]
Hello
Thank you for development. Now we have python 3.7 support!
I try to build deps for Sverchok https://github.com/nortikin/sverchok/wiki/Dependencies
There is sudo echo '/usr/lib/x86_64-linux-gnu/netgen' >> /etc/ld.so.conf.d/x86_64-linux-gnu.conf   
netgen
I think i need this flag
But with netgen freecad don't builds 
https://gist.github.com/0ffa2711b784ac1ee2f09f281176a8ad

**Comment by brothermechanic** [comment]
with freecad-0.18 same problem
https://gist.github.com/f6e662ec31da724047b85c56aefae782

**Comment by waebbl** [comment]
Closing. Netgen is currently not available in my overlay or in ::gentoo.
