### ISSUE TITLE
media-gfx/freecad-0.18.4-r1: emerge failed because DAGView.cpp:64:103: error: ‘_1’ was not declared in this scope

### ISSUE THREAD

**Issue by vowstar** [waebbl/waebbl-gentoo#250]
**Describe the bug**
emerge media-gfx/freecad and failed. The reason is 

```
/var/tmp/portage/media-gfx/freecad-0.18.4-r1/work/FreeCAD-0.18.4/src/Gui/DAGView/DAGView.cpp:64:103: error: ‘_1’ was not declared in this scope
```

**Please always add the following information (attach them or provide a link where they can be found). Bug reports without these information are considered invalid and will be closed:**
 - build log

[build.log](https://github.com/waebbl/waebbl-gentoo/files/5150530/build.log)

 - output of emerge --info

[emerge-info.log](https://github.com/waebbl/waebbl-gentoo/files/5150542/emerge-info.log)

**Additional context**

This error seems look like https://www.spinics.net/lists/fedora-devel/msg272306.html

**Comment by brothermechanic** [comment]
Same https://gist.github.com/fca419ecdc41882e9834f736fe1a6526
