### ISSUE TITLE
vtk 8.2.0-r2 does not compile

### ISSUE THREAD

**Issue by sylmio** [waebbl/waebbl-gentoo#259]
There seems to be a patch proposed to solve this problem
https://gitlab.kitware.com/vtk/vtk/-/issues/18033

Partial output of the error
TK-8.2.0/Utilities/KWSys -IThirdParty/utf8 -I/var/tmp/portage/sci-libs/vtk-8.2.0-r2/work/VTK-8.2.0/ThirdParty/utf8 -ICommon/DataModel -I/var/tmp/portage/sci-libs/vtk-8.2.0-r2/work/VTK-8.2.0/Common/DataModel -ICommon/Math -I/var/tmp/portage/sci-libs/vtk-8.2.0-r2/work/VTK-8.2.0/Common/Math -ICommon/Misc -I/var/tmp/portage/sci-libs/vtk-8.2.0-r2/work/VTK-8.2.0/Common/Misc -ICommon/System -I/var/tmp/portage/sci-libs/vtk-8.2.0-r2/work/VTK-8.2.0/Common/System -ICommon/Transforms -I/var/tmp/portage/sci-libs/vtk-8.2.0-r2/work/VTK-8.2.0/Common/Transforms -ICommon/ExecutionModel -I/var/tmp/portage/sci-libs/vtk-8.2.0-r2/work/VTK-8.2.0/Common/ExecutionModel -IFilters/General -I/var/tmp/portage/sci-libs/vtk-8.2.0-r2/work/VTK-8.2.0/Filters/General -ICommon/ComputationalGeometry -I/var/tmp/portage/sci-libs/vtk-8.2.0-r2/work/VTK-8.2.0/Common/ComputationalGeometry -IFilters/Core -I/var/tmp/portage/sci-libs/vtk-8.2.0-r2/work/VTK-8.2.0/Filters/Core -IRendering/Core -I/var/tmp/portage/sci-libs/vtk-8.2.0-r2/work/VTK-8.2.0/Rendering/Core -ICommon/Color -I/var/tmp/portage/sci-libs/vtk-8.2.0-r2/work/VTK-8.2.0/Common/Color -IFilters/Geometry -I/var/tmp/portage/sci-libs/vtk-8.2.0-r2/work/VTK-8.2.0/Filters/Geometry -IFilters/Sources -I/var/tmp/portage/sci-libs/vtk-8.2.0-r2/work/VTK-8.2.0/Filters/Sources -IThirdParty/freetype -I/var/tmp/portage/sci-libs/vtk-8.2.0-r2/work/VTK-8.2.0/ThirdParty/freetype -I/usr/include/freetype2 -IThirdParty/zlib -I/var/tmp/portage/sci-libs/vtk-8.2.0-r2/work/VTK-8.2.0/ThirdParty/zlib  -D__STDC_CONSTANT_MACROS -D_UNICODE -march=native -O2 -pipe  -fPIC -fvisibility=hidden   -std=c++11 -MD -MT Rendering/FreeType/CMakeFiles/vtkRenderingFreeType.dir/vtkFreeTypeTools.cxx.o -MF Rendering/FreeType/CMakeFiles/vtkRenderingFreeType.dir/vtkFreeTypeTools.cxx.o.d -o Rendering/FreeType/CMakeFiles/vtkRenderingFreeType.dir/vtkFreeTypeTools.cxx.o -c /var/tmp/portage/sci-libs/vtk-8.2.0-r2/work/VTK-8.2.0/Rendering/FreeType/vtkFreeTypeTools.cxx
FAILED: Rendering/FreeType/CMakeFiles/vtkRenderingFreeType.dir/vtkFreeTypeTools.cxx.o 
/usr/bin/x86_64-pc-linux-gnu-g++ -DVTK_IN_VTK -DvtkRenderingFreeType_EXPORTS -IRendering/FreeType -I/var/tmp/portage/sci-libs/vtk-8.2.0-r2/work/VTK-8.2.0/Rendering/FreeType -ICommon/Core -I/var/tmp/portage/sci-libs/vtk-8.2.0-r2/work/VTK-8.2.0/Common/Core -IUtilities/KWIML -I/var/tmp/portage/sci-libs/vtk-8.2.0-r2/work/VTK-8.2.0/Utilities/KWIML -IUtilities/KWSys -I/var/tmp/portage/sci-libs/vtk-8.2.0-r2/work/VTK-8.2.0/Utilities/KWSys -IThirdParty/utf8 -I/var/tmp/portage/sci-libs/vtk-8.2.0-r2/work/VTK-8.2.0/ThirdParty/utf8 -ICommon/DataModel -I/var/tmp/portage/sci-libs/vtk-8.2.0-r2/work/VTK-8.2.0/Common/DataModel -ICommon/Math -I/var/tmp/portage/sci-libs/vtk-8.2.0-r2/work/VTK-8.2.0/Common/Math -ICommon/Misc -I/var/tmp/portage/sci-libs/vtk-8.2.0-r2/work/VTK-8.2.0/Common/Misc -ICommon/System -I/var/tmp/portage/sci-libs/vtk-8.2.0-r2/work/VTK-8.2.0/Common/System -ICommon/Transforms -I/var/tmp/portage/sci-libs/vtk-8.2.0-r2/work/VTK-8.2.0/Common/Transforms -ICommon/ExecutionModel -I/var/tmp/portage/sci-libs/vtk-8.2.0-r2/work/VTK-8.2.0/Common/ExecutionModel -IFilters/General -I/var/tmp/portage/sci-libs/vtk-8.2.0-r2/work/VTK-8.2.0/Filters/General -ICommon/ComputationalGeometry -I/var/tmp/portage/sci-libs/vtk-8.2.0-r2/work/VTK-8.2.0/Common/ComputationalGeometry -IFilters/Core -I/var/tmp/portage/sci-libs/vtk-8.2.0-r2/work/VTK-8.2.0/Filters/Core -IRendering/Core -I/var/tmp/portage/sci-libs/vtk-8.2.0-r2/work/VTK-8.2.0/Rendering/Core -ICommon/Color -I/var/tmp/portage/sci-libs/vtk-8.2.0-r2/work/VTK-8.2.0/Common/Color -IFilters/Geometry -I/var/tmp/portage/sci-libs/vtk-8.2.0-r2/work/VTK-8.2.0/Filters/Geometry -IFilters/Sources -I/var/tmp/portage/sci-libs/vtk-8.2.0-r2/work/VTK-8.2.0/Filters/Sources -IThirdParty/freetype -I/var/tmp/portage/sci-libs/vtk-8.2.0-r2/work/VTK-8.2.0/ThirdParty/freetype -I/usr/include/freetype2 -IThirdParty/zlib -I/var/tmp/portage/sci-libs/vtk-8.2.0-r2/work/VTK-8.2.0/ThirdParty/zlib  -D__STDC_CONSTANT_MACROS -D_UNICODE -march=native -O2 -pipe  -fPIC -fvisibility=hidden   -std=c++11 -MD -MT Rendering/FreeType/CMakeFiles/vtkRenderingFreeType.dir/vtkFreeTypeTools.cxx.o -MF Rendering/FreeType/CMakeFiles/vtkRenderingFreeType.dir/vtkFreeTypeTools.cxx.o.d -o Rendering/FreeType/CMakeFiles/vtkRenderingFreeType.dir/vtkFreeTypeTools.cxx.o -c /var/tmp/portage/sci-libs/vtk-8.2.0-r2/work/VTK-8.2.0/Rendering/FreeType/vtkFreeTypeTools.cxx
/var/tmp/portage/sci-libs/vtk-8.2.0-r2/work/VTK-8.2.0/Rendering/FreeType/vtkFreeTypeTools.cxx:391:1: error: expected constructor, destructor, or type conversion before ‘vtkFreeTypeToolsFaceRequester’
  391 | vtkFreeTypeToolsFaceRequester(FTC_FaceID face_id,
      | ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/var/tmp/portage/sci-libs/vtk-8.2.0-r2/work/VTK-8.2.0/Rendering/FreeType/vtkFreeTypeTools.cxx: In member function ‘virtual FT_Error vtkFreeTypeTools::CreateFTCManager()’:
/var/tmp/portage/sci-libs/vtk-8.2.0-r2/work/VTK-8.2.0/Rendering/FreeType/vtkFreeTypeTools.cxx:1252:26: error: ‘vtkFreeTypeToolsFaceRequester’ was not declared in this scope; did you mean ‘vtkFreeTypeToolsCleanupCounter’?
 1252 |                          vtkFreeTypeToolsFaceRequester,
      |                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                          vtkFreeTypeToolsCleanupCounter
ninja: build stopped: subcommand failed.
 * ERROR: sci-libs/vtk-8.2.0-r2::waebbl failed (compile phase):
 *   ninja -v -j3 -l2 failed
 * 
 * Call stack:
 *     ebuild.sh, line  125:  Called src_compile
 *   environment, line 5180:  Called cmake_src_compile
 *   environment, line 1419:  Called cmake_build
 *   environment, line 1388:  Called eninja
 *   environment, line 1997:  Called die
 * The specific snippet of code:
 *       "$@" || die "${nonfatal_args[@]}" "${*} failed"
 * 
 * If you need support, post the output of `emerge --info '=sci-libs/vtk-8.2.0-r2::waebbl'`,
 * the complete build log and the output of `emerge -pqv '=sci-libs/vtk-8.2.0-r2::waebbl'`.
!!! When you file a bug report, please include the following information:
GENTOO_VM=  CLASSPATH="" JAVA_HOME=""
JAVACFLAGS="" COMPILER=""
and of course, the output of emerge --info =vtk-8.2.0
 * The complete build log is located at '/var/tmp/portage/sci-libs/vtk-8.2.0-r2/temp/build.log'.
 * The ebuild environment file is located at '/var/tmp/portage/sci-libs/vtk-8.2.0-r2/temp/environment'.
 * Working directory: '/var/tmp/portage/sci-libs/vtk-8.2.0-r2/work/vtk-8.2.0_build'
 * S: '/var/tmp/portage/sci-libs/vtk-8.2.0-r2/work/VTK-8.2.0'

**Comment by sylmio** [comment]
I included the patch in the previous link and available here https://gitlab.kitware.com/vtk/vtk/uploads/c6fa799a1a028b8f8a728a40d26d3fec/vtk-freetype-2.10.3-replace-FT_CALLBACK_DEF.patch
in the ebuild and compilation worked

**Comment by khumarahn** [comment]
Same here. Thanks for the patch, it helped.

**Comment by waebbl** [comment]
Thanks for reporting and pointing to the patch. I included the patch in the ebuild.
