### ISSUE TITLE
sci-libs/opencascade-7.5 update

### ISSUE THREAD

**Issue by khumarahn** [waebbl/waebbl-gentoo#269]
Hi.

This is not actually a bug. There is a new version of opencascade available, and I remember a few errors in freecad which were caused by opencascade. I wonder if there is any sense to update opencascade, and if anyone is looking into it.

**Comment by waebbl** [comment]
Thanks for pointing this out. I haven't been noticed yet about this. I'm gonna check the update and prepare a PR for it.

**Comment by waebbl** [comment]
Closing this. 7.5.{2,3} and 7.6 are in ::gentoo

**Comment by khumarahn** [comment]
Amazing, thank you!!!

**Comment by waebbl** [comment]
Thanks for your patience and sorry for overseeing this issue. The 7.5 package is actually in ::gentoo for quite some time.
