### ISSUE TITLE
freecad-0.18.5 boost-1.74.0-r1 compatibility...

### ISSUE THREAD

**Issue by CaptainBloodz** [waebbl/waebbl-gentoo#272]
0.18.4 fails to build here with gentoo stable boost-1.74.0-r1.
How does 0.18.5 behaves in this respect?

Thks 4 ur attention, interest & support.

**Comment by waebbl** [comment]
Hi @CaptainBloodz, I don't had problems building 0.18.4-r1 against boost-1.74.0-r1. Having had two rebuilds since this boost version was installed. Also had no issues building 0.18.5 against 1.74.0-r1.
What are the issues you are having with this boost?

**Comment by waebbl** [comment]
@CaptainBloodz Please try again with 0.18.5-r1. If the issue persists, feel free to re-open the issue.

**Comment by CaptainBloodz** [comment]
NFO: USE=assembly caused the issue.
Currently using boost-1.74.0.
https://forums.gentoo.org/viewtopic-t-1125022-highlight-.html

Thks 4 ur attention, interest & support.

**Comment by waebbl** [comment]
Assembly USE flag is masked in my overlay. So if you were able to activate this USE flag, you haven't been using the ebuild from my overlay.
Could you post a build log?
