### ISSUE TITLE
Frecad 18.5 and Python 3.8 build error

### ISSUE THREAD

**Issue by SimonLitt** [waebbl/waebbl-gentoo#273]
Hi!
I have the following build error:

/var/tmp/portage/media-gfx/freecad-0.18.5/work/FreeCAD-0.18.5/src/Base/swigpyrun.inl:75:31: error: invalid use of incomplete type ‘PyInterpreterState’ {aka «struct _is»}
   75 |     PyObject *modules = interp->modules;
      |                               ^~
In file included from /usr/include/python3.8/genobject.h:11,
                 from /usr/include/python3.8/Python.h:121,
                 from /var/tmp/portage/media-gfx/freecad-0.18.5/work/FreeCAD-0.18.5/src/Base/PyExport.h:42,
                 from /var/tmp/portage/media-gfx/freecad-0.18.5/work/FreeCAD-0.18.5/src/Base/swigpyrun.cpp:25:

At the `master` branch it already fixed:

https://github.com/FreeCAD/FreeCAD/commit/6eacb17b3e03d20039b85c9daebab9e44386d6bf?branch=6eacb17b3e03d20039b85c9daebab9e44386d6bf&diff=unified

**Comment by waebbl** [comment]
Hi @SimonLitt, thanks for the hint and your research upstream.
I will add the patch some time this week and update the ebuild.
