### ISSUE TITLE
No dev-python/pyside2-tools for FreeCAD

### ISSUE THREAD

**Issue by Petross404** [waebbl/waebbl-gentoo#279]
Hello, I hope you are all doing well. I noticed that dev-python/pyside2-tools is needed. I can fetch it form another overlay in my repo but I wanted to ask if there are any plans to create one in yours.

```
$ sudo PYTHON_SINGLE_TARGET="python3_8" emerge -av media-gfx/freecad

These are the packages that would be merged, in reverse order:

Calculating dependencies... done!

emerge: there are no ebuilds to satisfy "dev-python/pyside2-tools[python_targets_python3_8(-)]".
(dependency required by "media-gfx/freecad-0.18.5-r2::waebbl[python_single_target_python3_8]" [ebuild])
(dependency required by "media-gfx/freecad" [argument])
```

Maybe I could create a PR?

**Comment by waebbl** [comment]
Hi @Petross404 the build is no longer needed. I just prepared a PR which removes the dependency, it's just not merged yet. Also the pyside2-tools has been recently added to the ::gentoo tree, so you should be able to use this one and no longer need to fetch it from the ::raiagent or any other overlay.

**Comment by waebbl** [comment]
@Petross404 please sync and try again.
Feel free to re-open, if you still have issues.
