### ISSUE TITLE
media-gfx/freecad-0.18.4-r1: failed to build with sci-libs/vtk-9.0.0

### ISSUE THREAD

**Issue by vowstar** [waebbl/waebbl-gentoo#287]
**Describe the bug**
When update to  sci-libs/vtk-9.0.0, media-gfx/freecad failed to build with sci-libs/vtk-9.0.0

**Please always add the following information (attach them or provide a link where they can be found). Bug reports without these information are considered invalid and will be closed:**
 - build log [build.log](https://github.com/waebbl/waebbl-gentoo/files/5752884/build.log)
 - output of ``emerge --info =media-gfx/freecad-0.18.4-r1::waebbl``  [emerge-info.log](https://github.com/waebbl/waebbl-gentoo/files/5752889/emerge-info.log)

**Additional context**
Shoud limit version to sci-libs/vtk-8.2.0-r1

**Comment by vowstar** [comment]
Upgrademedia-gfx/freecad-0.18.4 to media-gfx/freecad-0.18.5 and downgrade sci-libs/vtk-9.0.0 to sci-libs/vtk-8.2.0

**Comment by waebbl** [comment]
Packages which are not in ::gentoo or the local overlay should usually be masked using `/etc/portage/package.mask` and not by limiting the dependency.
