### ISSUE TITLE
media-gfx/freecad-0.18.5 build failed with dev-libs/boost-1.75.0

### ISSUE THREAD

**Issue by vowstar** [waebbl/waebbl-gentoo#288]
**Describe the bug**

After upgrade boost to dev-libs/boost-1.75.0, the media-gfx/freecad-0.18.5 build failed.

**Please always add the following information (attach them or provide a link where they can be found). Bug reports without these information are considered invalid and will be closed:**
 - build log 
 
[build.log](https://github.com/waebbl/waebbl-gentoo/files/5753682/build.log)

**Additional context**

``simage`` should add as ``RDEPEND`` with sndfile USE flag to prevent ``undefined reference to `sf_command'``

``media-libs/simage[sndfile]``

``BUILD_ENABLE_CXX_STD`` should be `` "C++14" `` when using boost-1.75.0 to fix ``error: expected template-name before ‘<’ token C++14``

**Comment by waebbl** [comment]
@vowstar Thanks for reporting. 
- FreeCAD does not depend on simage, coin does and pulls it in. So we should not add a hard-dependency on this package. The issue with the simage package has been fixed in simage-1.8.0-r1 and 0.18.5 has been tested to work with this version.
- I'm currently updating my system, which includes boost-1.75.0 and then look at this bug.
- Your boost-related patch looks good. 
- We could also update dependency on vtk, although vtk-9 isn't in the official tree yet, nor in my overlay. so there's no possibility for the ebuild to pull in vtk-9 package. If a user has vtk-9 in another repo, the package should usually be masked by means of `/etc/portage/package.mask` file(s). But it's safe to limit the version like this, so we can leave it in.

**Comment by vowstar** [comment]
Thanks for reply.
When I emerge  ``media-gfx/freecad-0.18.5-r2``, it pulled  simage-1.8.0-r1, but by default it have no ``sndfile`` use flag. In my build log, without ``sndfile`` use, the `media-gfx/freecad-0.18.5-r2`` compile failed with `` undefined reference`` error, so it depend  ``sndfile`` use flag to ``simage-1.8.0-r1``. After I add this use flag manually, it fixed.
```
: && /usr/bin/x86_64-pc-linux-gnu-g++ -Wall -Wextra -Wno-write-strings -march=native -O2 -pipe -std=c++14 -D_OCC64 -Wl,-O1 -Wl,--as-needed    -rdynamic src/Main/CMakeFiles/FreeCADMain.dir/MainGui.cpp.o -o bin/FreeCAD  -Wl,-rpath,/var/tmp/portage/media-gfx/freecad-0.18.5-r2/work/freecad-0.18.5_build/lib:  lib/libFreeCADGui.so  lib/libFreeCADApp.so  lib/libFreeCADBase.so  /usr/lib64/libpython3.7m.so  /usr/lib64/libxerces-c.so  -lz  -lutil  -ldl  /usr/lib64/libQt5Xml.so.5.15.2  /usr/lib64/libCoin.so  /usr/lib64/libboost_filesystem-mt.so  /usr/lib64/libboost_program_options-mt.so  /usr/lib64/libboost_regex-mt.so  /usr/lib64/libboost_system-mt.so  /usr/lib64/libboost_thread-mt.so  /usr/lib64/libboost_chrono-mt.so  /usr/lib64/libboost_date_time-mt.so  /usr/lib64/libboost_atomic-mt.so  -lpthread  /usr/lib64/libQt5OpenGL.so.5.15.2  /usr/lib64/libQt5PrintSupport.so.5.15.2  /usr/lib64/libQt5Svg.so.5.15.2  /usr/lib64/libQt5Network.so.5.15.2  /usr/lib64/libQt5UiTools.a  /usr/lib64/libQt5Widgets.so.5.15.2  /usr/lib64//libQt5Widgets.so  /usr/lib64//libQt5Gui.so  /usr/lib64//libQt5Core.so  /usr/lib64//libQt5Widgets.so  /usr/lib64//libQt5Gui.so  /usr/lib64//libQt5Core.so  /usr/lib64/libGL.so  -lpthread  /usr/lib64/libQt5X11Extras.so.5.15.2  /usr/lib64/libQt5Gui.so.5.15.2  /usr/lib64/libQt5Core.so.5.15.2  /usr/lib64/libspnav.so  /usr/lib64/libX11.so  -lshiboken2-python3.7  -lpyside2-python3.7 && :
/usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: /usr/lib64/libsimage.so.20: undefined reference to `sf_open'
/usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: /usr/lib64/libsimage.so.20: undefined reference to `sf_seek'
/usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: /usr/lib64/libsimage.so.20: undefined reference to `sf_close'
/usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: /usr/lib64/libsimage.so.20: undefined reference to `sf_read_double'
/usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: /usr/lib64/libsimage.so.20: undefined reference to `sf_command'
collect2: error: ld returned 1 exit status
```

**Comment by waebbl** [comment]
Thanks for these details. Then it looks, like the simage is still not working as expected. I have the `USE=sndfile` enabled  by default, so I need to test this in my test environment. This will take some time, as I have a world update with lots of packages running on my desktop environment, which is the on the same machine and freecad has ~200 dependencies needed to pull in on the test environment.

Could you please provide the output of `lddtree /usr/lib64/libsimage.so` and `emerge -pv simage`?

**Comment by waebbl** [comment]
You're right, just build simage in my test environment and the automagic dependency on libsndfile isn't properly fixed. If libsndfile is installed on the system, it will detect it and include support, even if the USE flag isn't set.
@fordfrog Looks like we need to review the automagic stuff in simage regarind libsndfile. I'm gonna check the patch for file it and try to include equivalent fixes for libsndfile.

**Comment by waebbl** [comment]
Well no, I was wrong. It detects it,
```
-- Found OggVorbis: /usr/include;/usr/include  
-- Found Sndfile: /usr/lib64/libsndfile.so  
-- Looking for include file dlfcn.h
```
but doesn't link to it:
```
[41/42] : && /usr/bin/x86_64-pc-linux-gnu-gcc -fPIC -O2 -pipe -march=bdver2 -frecord-gcc-switches -fstack-check -fstack-protector-strong  -Wl,-O1 -Wl,--as-needed -Wl,--defsym=__gentoo_check_ldflags__=0 -shared -Wl,-soname,libsimage.so.20 -o lib/libsimage.so.1.8.0 CMakeFiles/simage.dir/src/avi_encode.c.o CMakeFiles/simage.dir/src/movie.c.o CMakeFiles/simage.dir/src/params.c.o CMakeFiles/simage.dir/src/resize.c.o CMakeFiles/simage.dir/src/simage.c.o CMakeFiles/simage.dir/src/simage_avi.c.o CMakeFiles/simage.dir/src/simage_eps.c.o CMakeFiles/simage.dir/src/simage_jasper.c.o CMakeFiles/simage.dir/src/simage_libsndfile.c.o CMakeFiles/simage.dir/src/simage_oggvorbis_reader.c.o CMakeFiles/simage.dir/src/simage_pic.c.o CMakeFiles/simage.dir/src/simage_rgb.c.o CMakeFiles/simage.dir/src/simage_write.c.o CMakeFiles/simage.dir/src/simage_xwd.c.o CMakeFiles/simage.dir/src/simage12.c.o CMakeFiles/simage.dir/src/simage13.c.o CMakeFiles/simage.dir/src/stream.c.o CMakeFiles/simage.dir/mpeg2enc/api.c.o CMakeFiles/simage.dir/mpeg2enc/conform.c.o CMakeFiles/simage.dir/mpeg2enc/fdctref.c.o CMakeFiles/simage.dir/mpeg2enc/idct.c.o CMakeFiles/simage.dir/mpeg2enc/motion.c.o CMakeFiles/simage.dir/mpeg2enc/predict.c.o CMakeFiles/simage.dir/mpeg2enc/putbits.c.o CMakeFiles/simage.dir/mpeg2enc/puthdr.c.o CMakeFiles/simage.dir/mpeg2enc/putmpg.c.o CMakeFiles/simage.dir/mpeg2enc/putpic.c.o CMakeFiles/simage.dir/mpeg2enc/putseq.c.o CMakeFiles/simage.dir/mpeg2enc/putvlc.c.o CMakeFiles/simage.dir/mpeg2enc/quantize.c.o CMakeFiles/simage.dir/mpeg2enc/ratectl.c.o CMakeFiles/simage.dir/mpeg2enc/readpic.c.o CMakeFiles/simage.dir/mpeg2enc/stats.c.o CMakeFiles/simage.dir/mpeg2enc/transfrm.c.o CMakeFiles/simage.dir/mpeg2enc/writepic.c.o CMakeFiles/simage.dir/src/simage_tga.c.o CMakeFiles/simage.dir/src/simage_gif.c.o CMakeFiles/simage.dir/src/simage_jpeg.c.o CMakeFiles/simage.dir/src/simage_png.c.o CMakeFiles/simage.dir/src/simage_tiff.c.o   && :
```
and
```
(chroot64) # lddtree /usr/lib64/libsimage.so
libsimage.so => /usr/lib64/libsimage.so (interpreter => none)
    libc.so.6 => /lib64/libc.so.6
        ld-linux-x86-64.so.2 => /lib64/ld-linux-x86-64.so.2
```

**Comment by fordfrog** [comment]
@waebbl does the live ebuild behave differently?

**Comment by waebbl** [comment]
Yes, but I used the ::gentoo 1.8.0-r1 ebuild for the test. The live ebuild doesn't even search for and doesn't report libraries, when the USE flag isn't set. Upstream has introduced a lot of checks for the upcoming 1.8.1 release and on my testing there were no more automagic dependencies. But my alarm on comment https://github.com/waebbl/waebbl-gentoo/issues/288#issuecomment-752675876 was a false alarm, as my last comment shows.

**Comment by brothermechanic** [comment]
@vowstar thanks, works great!

**Comment by waebbl** [comment]
cf https://forum.freecadweb.org/viewtopic.php?f=4&t=53642

**Comment by waebbl** [comment]
I can not reproduce the sndfile issue. I rebuild simage without support for sndfile and freecad built without issues, after the patch for boost-1.75.0 was applied. I was using my new 0.19 ebuild for that test, but this shouldn't matter.
I'm adding the boost patch and restrict vtk dependency, those were good additions, but I won't add the unneeded simage dependency. The issue is somewhere else, as freecad doesn't depend at all on simage.
Thanks @vowstar!

**Comment by vowstar** [comment]
After fully upgrade system, I remove the USE of sndfile, and rebuild simage, restart computer, reinstall freecad, and failed again.
Under my environment, this issue always re-produced if the ``simage-1.8.0-r1`` without ``USE=sndfile``

The ``lddtree /usr/lib64/libsimage.so > lddtree.log``:

[lddtree.log](https://github.com/waebbl/waebbl-gentoo/files/5758892/lddtree.log)

The ``emerge -pv simage > emerge-pv-simage.log``

[emerge-pv-simage.log](https://github.com/waebbl/waebbl-gentoo/files/5758893/emerge-pv-simage.log)

The ``emerge --info =media-gfx/freecad-0.18.4-r1::waebbl > emerge-info.log``:

[emerge-info.log](https://github.com/waebbl/waebbl-gentoo/files/5758899/emerge-info.log)


The log of freecad build(latest from weabbl overlay``/var/tmp/portage/media-gfx/freecad-0.18.5-r2/temp/build.log`` ):

[build.log](https://github.com/waebbl/waebbl-gentoo/files/5758901/build.log)

```
[2410/3179] : && /usr/bin/x86_64-pc-linux-gnu-g++ -Wall -Wextra -Wno-write-strings -march=native -O2 -pipe -std=c++14 -D_OCC64 -Wl,-O1 -Wl,--as-needed    -rdynamic src/Main/CMakeFiles/FreeCADMain.dir/MainGui.cpp.o -o bin/FreeCAD  -Wl,-rpath,/var/tmp/portage/media-gfx/freecad-0.18.5-r2/work/freecad-0.18.5_build/lib:  lib/libFreeCADGui.so  lib/libFreeCADApp.so  lib/libFreeCADBase.so  /usr/lib64/libpython3.8.so  /usr/lib64/libxerces-c.so  -lz  -lutil  -ldl  /usr/lib64/libQt5Xml.so.5.15.2  /usr/lib64/libCoin.so  /usr/lib64/libboost_filesystem-mt.so  /usr/lib64/libboost_program_options-mt.so  /usr/lib64/libboost_regex-mt.so  /usr/lib64/libboost_system-mt.so  /usr/lib64/libboost_thread-mt.so  /usr/lib64/libboost_chrono-mt.so  /usr/lib64/libboost_date_time-mt.so  /usr/lib64/libboost_atomic-mt.so  -lpthread  /usr/lib64/libQt5OpenGL.so.5.15.2  /usr/lib64/libQt5PrintSupport.so.5.15.2  /usr/lib64/libQt5Svg.so.5.15.2  /usr/lib64/libQt5Network.so.5.15.2  /usr/lib64/libQt5UiTools.a  /usr/lib64/libQt5Widgets.so.5.15.2  /usr/lib64//libQt5Widgets.so  /usr/lib64//libQt5Gui.so  /usr/lib64//libQt5Core.so  /usr/lib64//libQt5Widgets.so  /usr/lib64//libQt5Gui.so  /usr/lib64//libQt5Core.so  /usr/lib64/libGL.so  -lpthread  /usr/lib64/libQt5X11Extras.so.5.15.2  /usr/lib64/libQt5Gui.so.5.15.2  /usr/lib64/libQt5Core.so.5.15.2  /usr/lib64/libspnav.so  /usr/lib64/libX11.so  -lshiboken2-python3.8  -lpyside2-python3.8 && :
[31mFAILED: [0mbin/FreeCAD 
: && /usr/bin/x86_64-pc-linux-gnu-g++ -Wall -Wextra -Wno-write-strings -march=native -O2 -pipe -std=c++14 -D_OCC64 -Wl,-O1 -Wl,--as-needed    -rdynamic src/Main/CMakeFiles/FreeCADMain.dir/MainGui.cpp.o -o bin/FreeCAD  -Wl,-rpath,/var/tmp/portage/media-gfx/freecad-0.18.5-r2/work/freecad-0.18.5_build/lib:  lib/libFreeCADGui.so  lib/libFreeCADApp.so  lib/libFreeCADBase.so  /usr/lib64/libpython3.8.so  /usr/lib64/libxerces-c.so  -lz  -lutil  -ldl  /usr/lib64/libQt5Xml.so.5.15.2  /usr/lib64/libCoin.so  /usr/lib64/libboost_filesystem-mt.so  /usr/lib64/libboost_program_options-mt.so  /usr/lib64/libboost_regex-mt.so  /usr/lib64/libboost_system-mt.so  /usr/lib64/libboost_thread-mt.so  /usr/lib64/libboost_chrono-mt.so  /usr/lib64/libboost_date_time-mt.so  /usr/lib64/libboost_atomic-mt.so  -lpthread  /usr/lib64/libQt5OpenGL.so.5.15.2  /usr/lib64/libQt5PrintSupport.so.5.15.2  /usr/lib64/libQt5Svg.so.5.15.2  /usr/lib64/libQt5Network.so.5.15.2  /usr/lib64/libQt5UiTools.a  /usr/lib64/libQt5Widgets.so.5.15.2  /usr/lib64//libQt5Widgets.so  /usr/lib64//libQt5Gui.so  /usr/lib64//libQt5Core.so  /usr/lib64//libQt5Widgets.so  /usr/lib64//libQt5Gui.so  /usr/lib64//libQt5Core.so  /usr/lib64/libGL.so  -lpthread  /usr/lib64/libQt5X11Extras.so.5.15.2  /usr/lib64/libQt5Gui.so.5.15.2  /usr/lib64/libQt5Core.so.5.15.2  /usr/lib64/libspnav.so  /usr/lib64/libX11.so  -lshiboken2-python3.8  -lpyside2-python3.8 && :
/usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: /usr/lib64/libsimage.so.20: undefined reference to `sf_open'
/usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: /usr/lib64/libsimage.so.20: undefined reference to `sf_seek'
/usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: /usr/lib64/libsimage.so.20: undefined reference to `sf_close'
/usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: /usr/lib64/libsimage.so.20: undefined reference to `sf_read_double'
/usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: /usr/lib64/libsimage.so.20: undefined reference to `sf_command'
collect2: error: ld returned 1 exit status
```

**Comment by waebbl** [comment]
That's strange, especially as your libsimage.so doesn't link to sndfile at all as your output from `lddtree` clearly shows.

I noticed a `PRELINK_<x>` flag in your emerge info. Do you use prelink? I haven't used it for the last ~10-15 years, so I don't know how it works today or how often the libraries are prelinked. Might this be a source for the issue?

I rebuilt simage without sndfile support yesterday, and my 0.19 branch of freecad (not yet merged) built just fine with it.

**Comment by vowstar** [comment]
Yes it is very strange.
I grep the emerge --info, found that 

```bash
emerge --info =media-gfx/freecad-0.18.4-r1::waebbl | grep PRELINK
PRELINK_PATH_MASK="/usr/bin/evolution"
```
Then I test the prelink on my system:

```bash
which prelink     
prelink not found

sudo which prelink
...
which: no prelink in (/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin:/opt/bin:/usr/lib/llvm/11/bin:/opt/cuda/bin)

emerge --search prelink

*  sys-devel/prelink
      Latest version available: 20151030-r1
      Latest version installed: [ Not Installed ]
      Size of files: 685 KiB
      Homepage:      https://git.yoctoproject.org/cgit/cgit.cgi/prelink-cross/ https://people.redhat.com/jakub/prelink
      Description:   Modifies ELFs to avoid runtime symbol resolutions resulting in faster load times
      License:       GPL-2

```
 So the prelink not installed.

Then I try to trace what bring the ``PRELINK_PATH_MASK``, and found that

```bash

cat /etc/env.d/99evolution 
PRELINK_PATH_MASK=/usr/bin/evolution

qfile /etc/env.d/99evolution
mail-client/evolution: /etc/env.d/99evolution

```

This env file installed by mail-client/evolution

**Comment by waebbl** [comment]
Ok, so this is just a precautionary mechanism to avoid prelinking the evolution binary, in case prelink is installed. No harm.

**Comment by RayOfLight1** [comment]
> Thanks for reply.
> When I emerge `media-gfx/freecad-0.18.5-r2`, it pulled `simage-1.8.0-r1` (by `media-libs/coin-4.0.0`), but by default it have no `sndfile` use flag. In my build log, without `sndfile` use, the `media-gfx/freecad-0.18.5-r2` compile failed with ` undefined reference` error, so it depend `sndfile` use flag to `simage-1.8.0-r1`. After I add this use flag manually, it fixed.
> 
> ```
> : && /usr/bin/x86_64-pc-linux-gnu-g++ -Wall -Wextra -Wno-write-strings -march=native -O2 -pipe -std=c++14 -D_OCC64 -Wl,-O1 -Wl,--as-needed    -rdynamic src/Main/CMakeFiles/FreeCADMain.dir/MainGui.cpp.o -o bin/FreeCAD  -Wl,-rpath,/var/tmp/portage/media-gfx/freecad-0.18.5-r2/work/freecad-0.18.5_build/lib:  lib/libFreeCADGui.so  lib/libFreeCADApp.so  lib/libFreeCADBase.so  /usr/lib64/libpython3.7m.so  /usr/lib64/libxerces-c.so  -lz  -lutil  -ldl  /usr/lib64/libQt5Xml.so.5.15.2  /usr/lib64/libCoin.so  /usr/lib64/libboost_filesystem-mt.so  /usr/lib64/libboost_program_options-mt.so  /usr/lib64/libboost_regex-mt.so  /usr/lib64/libboost_system-mt.so  /usr/lib64/libboost_thread-mt.so  /usr/lib64/libboost_chrono-mt.so  /usr/lib64/libboost_date_time-mt.so  /usr/lib64/libboost_atomic-mt.so  -lpthread  /usr/lib64/libQt5OpenGL.so.5.15.2  /usr/lib64/libQt5PrintSupport.so.5.15.2  /usr/lib64/libQt5Svg.so.5.15.2  /usr/lib64/libQt5Network.so.5.15.2  /usr/lib64/libQt5UiTools.a  /usr/lib64/libQt5Widgets.so.5.15.2  /usr/lib64//libQt5Widgets.so  /usr/lib64//libQt5Gui.so  /usr/lib64//libQt5Core.so  /usr/lib64//libQt5Widgets.so  /usr/lib64//libQt5Gui.so  /usr/lib64//libQt5Core.so  /usr/lib64/libGL.so  -lpthread  /usr/lib64/libQt5X11Extras.so.5.15.2  /usr/lib64/libQt5Gui.so.5.15.2  /usr/lib64/libQt5Core.so.5.15.2  /usr/lib64/libspnav.so  /usr/lib64/libX11.so  -lshiboken2-python3.7  -lpyside2-python3.7 && :
> /usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: /usr/lib64/libsimage.so.20: undefined reference to `sf_open'
> /usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: /usr/lib64/libsimage.so.20: undefined reference to `sf_seek'
> /usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: /usr/lib64/libsimage.so.20: undefined reference to `sf_close'
> /usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: /usr/lib64/libsimage.so.20: undefined reference to `sf_read_double'
> /usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: /usr/lib64/libsimage.so.20: undefined reference to `sf_command'
> collect2: error: ld returned 1 exit status
> ```

I was gonna open a new bug, but this fits in here: I too had the problem with sf_open and other undefied references when emerging media-gfx/freecad-0.18.5-r2, which after re-emerging media-libs/simage-1.8.0-r1 with USE=sndfile, made the process go trough without problems, so anyway, I leave my comment here to confirm vowstar' situation :+1: :-)

**Comment by waebbl** [comment]
This should be solved with the merge of https://github.com/waebbl/waebbl-gentoo/pull/293 and the update to simage-1.8.1.
Could you please test, whether these changes work for you?

**Comment by vowstar** [comment]
Thanks! I've tested and fixed.
