### ISSUE TITLE
Freecad, shiboken and python 3.8,3.9

### ISSUE THREAD

**Issue by khumarahn** [waebbl/waebbl-gentoo#309]
Emerging freecad fails with

```
# emerge -av1 freecad

These are the packages that would be merged, in order:

Calculating dependencies... done!
[ebuild   R   *] media-gfx/freecad-9999::waebbl  USE="addonmgr arch drawing fem idf image inspection material mesh openscad part-design path points raytracing robot show spreadsheet surface techdraw tux (-assembly) -debug -doc (-netgen) -oce -pcl -plot -ship" PYTHON_SINGLE_TARGET="python3_8 -python3_7" 0 KiB

Total: 1 package (1 reinstall), Size of downloads: 0 KiB

Would you like to merge these packages? [Yes/No] 

...

-- Shiboken2Config: Using default python: -python3.8
-- Found PythonInterp: /usr/bin/python3.9 (found suitable version "3.9.1", minimum required is "3") 
-- Found PythonLibs: /usr/lib64/libpython3.8.so (found suitable version "3.8.7", minimum required is "3") 
CMake Error at /usr/lib64/cmake/Shiboken2-5.15.1/shiboken_helpers.cmake:468 (message):
  The detected Python minor version is not compatible with the Python minor
  version which was used when Shiboken was built.  Consider building shiboken
  with FORCE_LIMITED_API set to '1', so that only the Python major version
  matters.

  Built with: '3.8' Detected: '3.9'
Call Stack (most recent call first):
  /usr/lib64/cmake/Shiboken2-5.15.1/Shiboken2Config-python3.8.cmake:55 (shiboken_check_if_built_and_target_python_are_compatible)
  /usr/lib64/cmake/Shiboken2-5.15.1/Shiboken2Config.cmake:5 (include)
  cMake/FreeCAD_Helpers/SetupShibokenAndPyside.cmake:13 (find_package)
  CMakeLists.txt:75 (SetupShibokenAndPyside)


-- Configuring incomplete, errors occurred!
```

I'm not sure where to look, the default python all around is 3.8

**Comment by waebbl** [comment]
Hmm, it says your shiboken2 is built with python-3.9. The shiboken2 from ::gentoo doesn't even have support for python-3.9. 
- Are you using this one? 
- Have you tried re-emerging shiboken2 to ensure proper python selection? 
- What's the output of emerge -pqv shiboken2?

**Comment by khumarahn** [comment]
I don't think shiboken was built with python 3.9. I use the `::gentoo` ebuild, nothing special I think.

```
# emerge -av1 shiboken2

These are the packages that would be merged, in order:

Calculating dependencies... done!
[ebuild   R   ~] dev-python/shiboken2-5.15.1::gentoo  USE="docstrings -numpy -test -vulkan" PYTHON_TARGETS="python3_8 -python3_7" 0 KiB
```
```
dev-python/shiboken2-5.15.1::gentoo was built with the following:
USE="docstrings -numpy -test -vulkan" ABI_X86="(64)" PYTHON_TARGETS="python3_8 -python3_7"
FEATURES="binpkg-docompress preserve-libs sfperms pid-sandbox userfetch news xattr userpriv ebuild-locks unmerge-logs unmerge-orphans assume-digests usersync unknown-features-warn ipc-sandbox protect-owned binpkg-dostrip binpkg-logs distlocks qa-unresolved-soname-deps config-protect-if-modified parallel-fetch usersandbox fixlafiles merge-sync multilib-strict sandbox strict"
```

**Comment by waebbl** [comment]
Thanks @khumarahn I'm gonna look into this.

**Comment by khumarahn** [comment]
Here is the commit which breaks the build: https://github.com/FreeCAD/FreeCAD/commit/e2782d0c20111b0563f6e66eb3a7dff1208fe1c5
Before it the error does not appear.

**Comment by khumarahn** [comment]
Here is an example of CMakeLists.txt which maybe is how python 3.9 makes its way into the the scene:
```
# these two are in freecad:
find_package(Python3 COMPONENTS Interpreter Development REQUIRED)
set(PYTHON_EXECUTABLE ${Python3_EXECUTABLE})

# and then shiboken:
include(/usr/lib64/cmake/Shiboken2-5.15.1/shiboken_helpers.cmake)
shiboken_find_required_python()
```
Detects
```
-- Found Python3: /usr/bin/python3.9 (found version "3.9.1") found components: Interpreter Development Development.Module Development.Embed 
-- Found PythonInterp: /usr/bin/python3.9 (found version "3.9.1") 
-- Found PythonLibs: /usr/lib64/libpython3.9.so (found version "3.9.1") 
```
instead of python 3.8.

Without the first 2 lines it detects python 3.8 as is normal.

**Comment by waebbl** [comment]
@khumarahn Thanks for your research. Looks like we have to pass `-DPython3_EXECUTABLE=${PYTHON}` in src_configure, like for many other packages as well, to tell cmake which python version has been selected by PYTHON_SINGLE_TARGET.
I'll look into this tomorrow, had a tough work schedule today and am too tired to make any meaningful changes this evening.

**Comment by khumarahn** [comment]
ok, no worries. I could compile some version of freecad, and I am happy in the meanwhile, even if it is a few commits old. I could not understand where to go next from what I found, it is good that you have ideas :-)

**Comment by waebbl** [comment]
@khumarahn Could you please try whether the commit on the live package in https://github.com/waebbl/waebbl-gentoo/pull/310 works? On my test there was no issue with python.

**Comment by khumarahn** [comment]
Yay, it make it past the configuration (where it was failing)!

**Comment by waebbl** [comment]
Thanks for testing. Then I merge the PR.

**Comment by khumarahn** [comment]
ok, many thanks!!! The rest of freecad is still compiling (and I will be working in freecad when it is done), but this particular issue seems fixed.

**Comment by waebbl** [comment]
Ok, closing this.
Github had issues with the merge. Although the files have been merged, the PR shows conflicts and this bug is not closed...
