### ISSUE TITLE
media-gfx/freecad-9999: file STRINGS file "/usr/include/opencascade/Standard_Version.hxx" cannot be read.

### ISSUE THREAD

**Issue by triffid** [waebbl/waebbl-gentoo#313]
**Describe the bug**
media-gfx/freecad-9999 fails with numerous cmake errors:

	-- The C compiler identification is GNU 10.2.0
	-- The CXX compiler identification is GNU 10.2.0
	-- Detecting C compiler ABI info
	-- Detecting C compiler ABI info - done
	-- Check for working C compiler: /usr/bin/x86_64-pc-linux-gnu-gcc - skipped
	-- Detecting C compile features
	-- Detecting C compile features - done
	-- Detecting CXX compiler ABI info
	-- Detecting CXX compiler ABI info - done
	-- Check for working CXX compiler: /usr/bin/x86_64-pc-linux-gnu-g++ - skipped
	-- Detecting CXX compile features
	-- Detecting CXX compile features - done
	-- Compiler: GNU, version: 10.2.0
	-- Looking for GL/gl.h
	-- Looking for GL/gl.h - found
	-- Looking for C++ include istream
	-- Looking for C++ include istream - found
	-- Looking for C++ include ostream
	-- Looking for C++ include ostream - found
	-- Looking for C++ include fstream
	-- Looking for C++ include fstream - found
	-- Looking for C++ include sstream
	-- Looking for C++ include sstream - found
	-- Looking for C++ include ios
	-- Looking for C++ include ios - found
	-- Looking for C++ include iostream
	-- Looking for C++ include iostream - found
	-- Looking for C++ include iomanip
	-- Looking for C++ include iomanip - found
	-- Looking for C++ include iostream
	-- Looking for C++ include iostream - found
	-- Check for STD namespace
	-- Check for STD namespace - found
	-- prefix: /usr/lib64/freecad
	-- bindir: bin
	-- datadir: /usr/share/freecad/data
	-- docdir: /usr/share/doc/freecad-9999
	-- includedir: /usr/include/freecad
	-- libdir: lib64
	-- cmake: 3.18.5
	-- Found Doxygen: /usr/bin/doxygen (found version "1.9.1") found components: doxygen missing components: dot
	-- Found Python3: /usr/bin/python3.8 (found version "3.8.9") found components: Interpreter Development Development.Module Development.Embed 
	-- Performing Test HAS_FLTO
	-- Performing Test HAS_FLTO - Success
	-- Found pybind11: /usr/include (found version "2.6.2" )
	-- Found XercesC: /usr/lib64/libxerces-c.so (found version "3.2.3") 
	-- Found ZLIB: /usr/lib64/libz.so (found version "1.2.11") 
	-- PyCXX found:
	--   Headers:  /var/tmp/portage/media-gfx/freecad-9999/work/freecad-9999/src
	--   Sources:  /var/tmp/portage/media-gfx/freecad-9999/work/freecad-9999/src/CXX
	--   Version:  6.2.8
	CMake Error at cMake/FindOpenCasCade.cmake:101 (file):
	file STRINGS file "/usr/include/opencascade/Standard_Version.hxx" cannot be
	read.
	Call Stack (most recent call first):
	cMake/FreeCAD_Helpers/SetupOpenCasCade.cmake:4 (find_package)
	CMakeLists.txt:51 (SetupOpenCasCade)

	CMake Error at cMake/FindOpenCasCade.cmake:104 (string):
	string sub-command REGEX, mode MATCH needs at least 5 arguments total to
	command.
	Call Stack (most recent call first):
	cMake/FreeCAD_Helpers/SetupOpenCasCade.cmake:4 (find_package)
	CMakeLists.txt:51 (SetupOpenCasCade)

	CMake Error at cMake/FindOpenCasCade.cmake:105 (file):
	file STRINGS file "/usr/include/opencascade/Standard_Version.hxx" cannot be
	read.
	Call Stack (most recent call first):
	cMake/FreeCAD_Helpers/SetupOpenCasCade.cmake:4 (find_package)
	CMakeLists.txt:51 (SetupOpenCasCade)

	CMake Error at cMake/FindOpenCasCade.cmake:108 (string):
	string sub-command REGEX, mode MATCH needs at least 5 arguments total to
	command.
	Call Stack (most recent call first):
	cMake/FreeCAD_Helpers/SetupOpenCasCade.cmake:4 (find_package)
	CMakeLists.txt:51 (SetupOpenCasCade)

	CMake Error at cMake/FindOpenCasCade.cmake:109 (file):
	file STRINGS file "/usr/include/opencascade/Standard_Version.hxx" cannot be
	read.
	Call Stack (most recent call first):
	cMake/FreeCAD_Helpers/SetupOpenCasCade.cmake:4 (find_package)
	CMakeLists.txt:51 (SetupOpenCasCade)

	CMake Error at cMake/FindOpenCasCade.cmake:112 (string):
	string sub-command REGEX, mode MATCH needs at least 5 arguments total to
	command.
	Call Stack (most recent call first):
	cMake/FreeCAD_Helpers/SetupOpenCasCade.cmake:4 (find_package)
	CMakeLists.txt:51 (SetupOpenCasCade)

	CMake Warning (dev) at /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:273 (message):
	The package name passed to `find_package_handle_standard_args` (OCC) does
	not match the name of the calling package (OpenCasCade).  This can lead to
	problems in calling code that expects `find_package` result variables
	(e.g., `_FOUND`) to follow a certain pattern.
	Call Stack (most recent call first):
	cMake/FindOpenCasCade.cmake:120 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
	cMake/FreeCAD_Helpers/SetupOpenCasCade.cmake:4 (find_package)
	CMakeLists.txt:51 (SetupOpenCasCade)
	This warning is for project developers.  Use -Wno-dev to suppress it.

	-- Found OCC: /usr/include/opencascade (found version "..") 
	-- -- Found OCE/OpenCASCADE version: ..
	-- -- OCE/OpenCASCADE include directory: /usr/include/opencascade
	-- -- OCE/OpenCASCADE shared libraries directory: /usr/lib64
	-- Found OpenGL: /usr/lib64/libOpenGL.so   
	-- Found OpenGLU: /usr/lib64/libGLU.so
	-- VTK components: vtkCommonCore;vtkCommonDataModel;vtkFiltersVerdict;vtkIOXML;vtkFiltersCore;vtkFiltersGeneral;vtkIOLegacy;vtkFiltersExtraction;vtkFiltersSources;vtkFiltersGeometry;vtkhdf5;vtkRenderingCore;vtkInteractionStyle;vtkRenderingFreeType;vtkRenderingOpenGL2
	-- Check for medfile (libmed and libmedc) ...
	-- Found MEDFile: /usr/include  
	-- Found PkgConfig: x86_64-pc-linux-gnu-pkg-config (found version "0.29.2") 
	-- We guess that libmed was built using hdf5-serial version
	-- Checking for one of the modules 'hdf5-serial'
	-- Found HDF5: /usr/lib64/libhdf5.so;/usr/lib64/libz.so;/usr/lib64/libdl.so;/usr/lib64/libm.so (found version "1.10.5")  
	-- Checking for one of the modules 'ompi-cxx'
	CMake Warning at cMake/FreeCAD_Helpers/SetupSalomeSMESH.cmake:104 (message):
	ompi-cxx was not found.  Check for error above.
	Call Stack (most recent call first):
	CMakeLists.txt:58 (SetupSalomeSMESH)

`/usr/include/opencascade` does not exist, but `/usr/include/opencascade-7.5.1` does - and eselect doesn't seem to provide a symlink

**Please always add the following information (attach them or provide a link where they can be found). Bug reports without these information are considered invalid and will be closed:**

[freecad-9999_build-log.txt](https://github.com/waebbl/waebbl-gentoo/files/6463935/freecad-9999_build-log.txt)

	# emerge -avt freecad
	These are the packages that would be merged, in reverse order:
	
	Calculating dependencies               ... done! 
	[ebuild   R   #] media-gfx/freecad-9999::waebbl  USE="addonmgr arch -cloud -debug drawing fem -headless idf image inspection material mesh openscad part-design path -pcl -plot points raytracing robot -ship show spreadsheet surface techdraw -test tux" PYTHON_SINGLE_TARGET="-python3_7 python3_8" 0 KiB
	
	Total: 1 package (1 reinstall), Size of downloads: 0 KiB

**Additional context**

Emerged on May 6th (6 days ago) without issue - no packages updated since then, just synced a few times

**Comment by waebbl** [comment]
Thanks for the report.
Looks like you have updated opencascade to 7.5.1 lately. I've added a patch in 0.19.2::gentoo a few days ago to handle opencascade selection correctly for both 7.4.0 and 7.5.1, which isn't yet ported the live ebuild, which is likely the cause of this issue.
