### ISSUE TITLE
how about python-3.7?

### ISSUE THREAD

**Issue by brothermechanic** [waebbl/waebbl-gentoo#32]
Well...)

**Comment by waebbl** [comment]
There are no stable python-3.7 packages yet in the tree. I do have python-3.7 installed already, but I'd refrain from unmasking a host of packages just for this.
I'm running stable and it will stay like this. Already spent too much time in the past in repairing errors from using ~amd64 globally. I don't have time for this.

**Comment by brothermechanic** [comment]
ok
i want to try new blender28 on python3.7
i will try update python)

**Comment by waebbl** [comment]
Ok, I will definitely come to add python3.7 support, once some basic python packages stabilize some more.

**Comment by brothermechanic** [comment]
i was susses update to python-3.7
almost all ebyulds are yours, just add 3.7
you can donload them from my overlay.

**Comment by waebbl** [comment]
I will take a look at it, but be prepared that this currently doesn't have a high priority, because adding a new PYTHON_COMPAT requires extensive testing. See https://wiki.gentoo.org/wiki/Project:Python/Adding_and_Removing_Python_implementations for ways how you can test the results of your changes.

**Comment by brothermechanic** [comment]
Hey!
When it be?

**Comment by waebbl** [comment]
As soon as it uses a versioned ebuild of python-exec. As long as it pulls
in the live ebuild, it won't happen


brothermechanic <notifications@github.com> schrieb am Mo., 29. Apr. 2019,
12:13:

**Comment by brothermechanic** [comment]
python-3.7, please.....((((

**Comment by waebbl** [comment]
I'm already at it. Boost 1.70.0 has been unmasked again, so I can finally add python3_7 support on several packages.

**Comment by brothermechanic** [comment]
Good, but i mean mainly for freecad package)
Please add 3.7 to freecad ebuild

**Comment by brothermechanic** [comment]
3.7 please....

**Comment by brothermechanic** [comment]
Campbell Barton suggests we should move to Python 3.8 for 2.82
https://www.blendernation.com/2019/10/29/blender-developer-notes-28-october-2019/

When it be?

**Comment by brothermechanic** [comment]
are you serious!?
It's just some kind of holiday

**Comment by waebbl** [comment]
What do you mean? In my country there's currently no holiday.

**Comment by brothermechanic** [comment]
this is a holiday for me personally)
I have been waiting for Python-3,7 support for more than 2 years!

**Comment by waebbl** [comment]
Well Nov 2018 to Jan 2020 is a little more than a year ;)
And although it's in freecad now, you effectively can't use it, because dev-python/autobahn is still missing python-3.7 support, but is pulled in by freecad.

**Comment by brothermechanic** [comment]
Oh, you are right
But this will be loong time for me)
>I'm pretty sure, it's not the only one
:( Sad
any day the blender will switch to python 3.8
and everything will be again....

**Comment by waebbl** [comment]
> any day the blender will switch to python 3.8
> and everything will be again....

I think the transition from 3.7 to 3.8 will be much faster than from 3.6 to 3.7. AFAIK 3.7 is more like 3.5 a short living development verion.
