### ISSUE TITLE
media-libs/coin-4.0.0a_pre20180921 - failure to clone subrepo

### ISSUE THREAD

**Issue by alexanderustinov** [waebbl/waebbl-gentoo#35]
Failure can be seen in attached build.log.
ls /usr/portage/distfiles/hg-src/Coin3D/generalmsvcgeneration gives no files
Please assist in debugging.

https://paste.pound-python.org/show/kTUFbvPTcyrd8v2qyzHY/

**Comment by alexanderustinov** [comment]
Sources were there from previous unsuccessful build. Before that there have been no sources. This Gentoo is 2 weeks old and is rather fresh.

hg update works like following https://paste.pound-python.org/show/3tDMjDFeFWDbiDmbzp5d/
After cloning from portage user i can see the work of hg clone:
> cloning subrepo build/general from /usr/portage/distfiles/hg-src/Coin3D/generalmsvcgeneration

`# ls /var/tmp/portage/media-libs/coin-4.0.0a_pre20180921/work/generalmsvcgeneration`
`Convert.js  generate-all.sh  generate.bat  generate-compiler.sh`

But emerge still falls with same 404 https://paste.pound-python.org/show/tpEQsnT1rLfzJSxtlARR/

**Comment by waebbl** [comment]
That's the same behaviour which I do get, when I try it. But it worked before. Also the mercurial eclass wasn't updated in a while and mercurial got last installed in july on my machine.
I would almost suppose, there must have been some changes to bitbucket. I noticed atlassian has changed quite a few things during the last couple of weeks, maybe they introduced some thing which made the current eclass implementation incompatible.

**Comment by waebbl** [comment]
Btw, if you need this for freecad (which is why I introduced the ebuild at the first place), the official tree now has a coin-4 ebuild too, which is, to my knowledge working with freecad.

**Comment by alexanderustinov** [comment]
Yes, it was for freecad. And yes official tree build works successfully.

Looking on 54 line in coin-9999 ebuild. Where does value for ${MY_P} come from?

**Comment by alexanderustinov** [comment]
Should i close this issue?

**Comment by waebbl** [comment]
> Yes, it was for freecad. And yes official tree build works successfully.
> 
> Looking on 54 line in coin-9999 ebuild. Where does value for ${MY_P} come from?

Good point, looks like this comes from an older version of the ebuild. I think, I forgot to change this line. Might be related to the issue. Please leave it open, I want to investigate this further.
Thanks for reporting! :+1:

**Comment by alexanderustinov** [comment]
It seems that said variable is not set. Thus mercurial tries to clone to nonempty directory and fails.

**Comment by waebbl** [comment]
I removed the line `MY_P=${P/c/C}` in https://github.com/waebbl/waebbl-gentoo/commit/c6d63aff6a3015238665ea431fd24ff4cff66ab9#diff-45438567a140f8cc3ee8ea25240ffbab
I will check this and try if it works, when I re-add the line.
