### ISSUE TITLE
media-gfx/freecad-9999 patch issue

### ISSUE THREAD

**Issue by evanfoss** [waebbl/waebbl-gentoo#355]
There is an issue with the freecad patchs in this ebuild. 
[build.log](https://github.com/waebbl/waebbl-gentoo/files/7916991/build.log)

Please fix the patchset.

>>> Emerging (2 of 2) media-gfx/freecad-9999::waebbl
 * freecad-9999-Gentoo-specific-fix-install-locations-of-Ext-and-Mod.patch.xz BLAKE2B SHA512 size ;-) ...                                                                                                                                              [ ok ]
 * Checking for at least 2 GiB disk space at "/tmp/portage/media-gfx/freecad-9999/temp" ...                                                                                                                                                            [ ok ]
 * Using python3.9 to build
>>> Unpacking source...
 * Repository id: FreeCAD_FreeCAD.git
 * To override fetched repository properties, use:
 *   EGIT_OVERRIDE_REPO_FREECAD_FREECAD
 *   EGIT_OVERRIDE_BRANCH_FREECAD_FREECAD
 *   EGIT_OVERRIDE_COMMIT_FREECAD_FREECAD
 *   EGIT_OVERRIDE_COMMIT_DATE_FREECAD_FREECAD
 * 
 * Fetching https://github.com/FreeCAD/FreeCAD.git ...
git fetch https://github.com/FreeCAD/FreeCAD.git +HEAD:refs/git-r3/HEAD
remote: Enumerating objects: 446, done.
remote: Counting objects: 100% (346/346), done.
remote: Compressing objects: 100% (26/26), done.
remote: Total 446 (delta 321), reused 338 (delta 320), pack-reused 100
Receiving objects: 100% (446/446), 579.55 KiB | 690.00 KiB/s, done.
Resolving deltas: 100% (359/359), completed with 100 local objects.
From https://github.com/FreeCAD/FreeCAD
   fdabaf692b..945602f187             -> refs/git-r3/HEAD
git symbolic-ref refs/git-r3/media-gfx/freecad/0/__main__ refs/git-r3/HEAD
 * Checking out https://github.com/FreeCAD/FreeCAD.git to /tmp/portage/media-gfx/freecad-9999/work/freecad-9999 ...
git checkout --quiet refs/git-r3/HEAD
GIT update -->
   repository:               https://github.com/FreeCAD/FreeCAD.git
   updating from commit:     fdabaf692b8cae4126a463ffe35da560f3ec078e
   to commit:                945602f18756b2152243140ac07adebce96eeafe
 src/App/Application.cpp                                            |  20 +++---
 src/App/Document.cpp                                               |  28 ++++----
 src/App/DocumentObjectPyImp.cpp                                    |  22 +------
 src/App/DocumentPyImp.cpp                                          | 120 ++++++++++++++++------------------
 src/App/DynamicProperty.cpp                                        |  24 ++++---
 src/App/FreeCADInit.py                                             |   8 ++-
 src/Base/Exception.cpp                                             |  38 ++++++-----
 src/Base/Exception.h                                               |  43 ++++++------
 src/Base/Interpreter.h                                             |  10 +--
 src/Base/PyObjectBase.h                                            |  19 +++---
 src/Base/Quantity.cpp                                              |  17 ++++-
 src/Base/Quantity.h                                                |   3 +-
 src/Base/QuantityPyImp.cpp                                         |  17 ++++-
 src/Base/Type.cpp                                                  |  13 ++++
 src/Base/Type.h                                                    |   2 +
 src/Base/TypePyImp.cpp                                             |  25 +++----
 src/Base/Unit.h                                                    |   2 +-
 src/Gui/ViewProviderLine.cpp                                       |   5 ++
 src/Gui/ViewProviderPlane.cpp                                      |   5 ++
 src/Mod/AddonManager/ALLOWED_PYTHON_PACKAGES.txt                   |  29 +++++++++
 src/Mod/AddonManager/AddonManager.py                               | 151 +++++++++++++++++++++++++++++++++++++-----
 src/Mod/AddonManager/AddonManagerOptions.ui                        |  43 +++++++++++-
 src/Mod/AddonManager/AddonManagerRepo.py                           |   9 +--
 src/Mod/AddonManager/CMakeLists.txt                                |   1 +
 src/Mod/AddonManager/addonmanager_metadata.py                      |  74 +++++++++++++++++++--
 src/Mod/AddonManager/addonmanager_utilities.py                     |   3 +-
 src/Mod/AddonManager/addonmanager_workers.py                       | 229 ++++++++++++++++++++++++++++++++++++++--------------------------
 src/Mod/AddonManager/dependency_resolution_dialog.ui               |   8 ++-
 src/Mod/Fem/Gui/AppFemGui.cpp                                      |   2 +
 src/Mod/Fem/Gui/CMakeLists.txt                                     |   3 +
 src/Mod/Fem/Gui/TaskFemConstraintOnBoundary.cpp                    |   5 ++
 src/Mod/Fem/Gui/ViewProviderFemConstraint.h                        |   3 +
 src/Mod/Fem/Gui/ViewProviderFemConstraintDisplacement.cpp          |   2 +-
 src/Mod/Fem/Gui/ViewProviderFemConstraintDisplacement.h            |   4 +-
 src/Mod/Fem/Gui/ViewProviderFemConstraintFixed.cpp                 |   2 +-
 src/Mod/Fem/Gui/ViewProviderFemConstraintFixed.h                   |   4 +-
 src/Mod/Fem/Gui/ViewProviderFemConstraintFluidBoundary.cpp         |   2 +-
 src/Mod/Fem/Gui/ViewProviderFemConstraintFluidBoundary.h           |   4 +-
 src/Mod/Fem/Gui/ViewProviderFemConstraintForce.cpp                 |   2 +-
 src/Mod/Fem/Gui/ViewProviderFemConstraintForce.h                   |   4 +-
 src/Mod/Fem/Gui/ViewProviderFemConstraintHeatflux.cpp              |   2 +-
 src/Mod/Fem/Gui/ViewProviderFemConstraintHeatflux.h                |   4 +-
 src/Mod/Fem/Gui/ViewProviderFemConstraintOnBoundary.cpp            | 128 ++++++++++++++++++++++++++++++++++++
 src/Mod/Fem/Gui/ViewProviderFemConstraintOnBoundary.h              |  51 +++++++++++++++
 src/Mod/Fem/Gui/ViewProviderFemConstraintPressure.cpp              |   2 +-
 src/Mod/Fem/Gui/ViewProviderFemConstraintPressure.h                |   4 +-
 src/Mod/Fem/Gui/ViewProviderFemConstraintSpring.cpp                |   2 +-
 src/Mod/Fem/Gui/ViewProviderFemConstraintSpring.h                  |   4 +-
 src/Mod/Fem/Gui/ViewProviderFemConstraintTemperature.cpp           |   2 +-
 src/Mod/Fem/Gui/ViewProviderFemConstraintTemperature.h             |   4 +-
 src/Mod/Part/App/Attacher.cpp                                      |  32 ++++++---
 src/Mod/Part/App/FeatureExtrusion.cpp                              | 117 +++++++++++++++++----------------
 src/Mod/Part/App/FeatureExtrusion.h                                |   6 +-
 src/Mod/Part/App/Geometry.cpp                                      |  10 +--
 src/Mod/Part/App/OpenCascadeAll.h                                  |   3 +
 src/Mod/Part/App/PreCompiled.h                                     |   1 -
 src/Mod/Part/App/Tools.cpp                                         |  57 ++++++++++++++++
 src/Mod/Part/App/Tools.h                                           |  22 +++++++
 src/Mod/Part/App/TopoShapeFacePyImp.cpp                            |  21 +++---
 src/Mod/Part/TestPartApp.py                                        |  25 +++++++
 src/Mod/Path/CMakeLists.txt                                        |  10 +++
 src/Mod/Path/Generators/drill_generator.py                         |   5 +-
 src/Mod/Path/Generators/helix_generator.py                         | 249 ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 src/Mod/Path/PathFeedRate.py                                       |  99 ++++++++++++++++++++++++++++
 src/Mod/Path/PathMachineState.py                                   | 135 ++++++++++++++++++++++++++++++++++++++
 src/Mod/Path/PathScripts/PathAreaOp.py                             |  14 ++--
 src/Mod/Path/PathScripts/PathCircularHoleBase.py                   | 101 ++++++-----------------------
 src/Mod/Path/PathScripts/PathDrilling.py                           | 233 ++++++++++++++++++++++++++++++++++++++++++++++-------------------
 src/Mod/Path/PathScripts/PathGeom.py                               |   3 +-
 src/Mod/Path/PathScripts/PathHelix.py                              |   4 +-
 src/Mod/Path/PathScripts/PathJob.py                                |  21 ++++++
 src/Mod/Path/PathScripts/PathPocketBase.py                         |   5 ++
 src/Mod/Path/PathScripts/PathPreferences.py                        |   2 +-
 src/Mod/Path/PathScripts/PathProfile.py                            |   7 +-
 src/Mod/Path/PathScripts/PathSelection.py                          | 167 ++++++++++++++++++++++++-----------------------
 src/Mod/Path/PathScripts/PathUtils.py                              | 390 +++++++++++--------------------------------------------------------------------------------------------------
 src/Mod/Path/PathScripts/PostUtils.py                              |  33 ++++++++++
 src/Mod/Path/PathScripts/drillableLib.py                           | 237 ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 src/Mod/Path/PathTests/Drilling_1.FCStd                            | Bin 0 -> 238841 bytes
 src/Mod/Path/PathTests/TestPathDrillGenerator.py                   |   4 ++
 src/Mod/Path/PathTests/TestPathDrillable.py                        | 313 +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 src/Mod/Path/PathTests/TestPathHelixGenerator.py                   | 183 +++++++++++++++++++++++++++++++++++++++++++++++++++
 src/Mod/Path/PathTests/TestPathHelpers.py                          | 139 +++++++++++++++++++++++++++++++++++++++
 src/Mod/Path/PathTests/TestPathPost.py                             |  88 +++++++++++++++++++------
 src/Mod/Path/TestPathApp.py                                        |  11 ++++
 src/Mod/Sketcher/Gui/ViewProviderSketch.cpp                        |  12 ++--
 src/Mod/TechDraw/App/Cosmetic.cpp                                  |  20 +-----
 src/Mod/TechDraw/App/Cosmetic.h                                    |   1 -
 src/Mod/TechDraw/App/DrawUtil.cpp                                  |   9 +++
 src/Mod/TechDraw/App/DrawUtil.h                                    |   1 +
 src/Mod/TechDraw/App/DrawViewDimension.cpp                         |  16 ++++-
 src/Mod/TechDraw/CMakeLists.txt                                    |  30 ++++++++-
 src/Mod/TechDraw/Gui/CMakeLists.txt                                |   5 ++
 src/Mod/TechDraw/Gui/CommandCreateDims.cpp                         |  12 ++--
 src/Mod/TechDraw/Gui/CommandExtensionDims.cpp                      |  16 ++++-
 src/Mod/TechDraw/Gui/CommandExtensionPack.cpp                      |  13 +---
 src/Mod/TechDraw/Gui/DlgPageChooser.ui                             |   2 +-
 src/Mod/TechDraw/Gui/Resources/TechDraw.qrc                        |   2 +
 src/Mod/TechDraw/Gui/Resources/icons/actions/TechDraw_CopyView.svg | 641 +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 src/Mod/TechDraw/Gui/Resources/icons/actions/TechDraw_MoveView.svg | 630 +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 src/Mod/TechDraw/Gui/TaskMoveView.ui                               | 101 +++++++++++++++++++++++++++++
 src/Mod/TechDraw/Gui/TaskSelectLineAttributes.cpp                  |  10 +++
 src/Mod/TechDraw/Gui/TaskSelectLineAttributes.h                    |   3 +
 src/Mod/TechDraw/Gui/TaskSelectLineAttributes.ui                   | 106 +++++++++++++++++-------------
 src/Mod/TechDraw/Gui/Workbench.cpp                                 |   8 +++
 src/Mod/TechDraw/InitGui.py                                        |   6 ++
 src/Mod/TechDraw/TechDrawTools/CommandCopyView.py                  |  90 +++++++++++++++++++++++++
 src/Mod/TechDraw/TechDrawTools/CommandMoveView.py                  |  89 +++++++++++++++++++++++++
 src/Mod/TechDraw/TechDrawTools/TDToolsMovers.py                    |  73 +++++++++++++++++++++
 src/Mod/TechDraw/TechDrawTools/TDToolsUtil.py                      |  38 +++++++++++
 src/Mod/TechDraw/TechDrawTools/TaskCopyView.py                     | 133 +++++++++++++++++++++++++++++++++++++
 src/Mod/TechDraw/TechDrawTools/TaskMoveView.py                     | 134 ++++++++++++++++++++++++++++++++++++++
 src/Mod/TechDraw/TechDrawTools/__init__.py                         |  38 +++++++++++
 src/Mod/Test/Document.py                                           |  19 ++++++
 src/Mod/Test/UnitTests.py                                          |   5 ++
 src/Tools/generateTemplates/templateClassPyExport.py               |  36 +---------
 116 files changed, 5100 insertions(+), 1154 deletions(-)
>>> Unpacking freecad-9999-Gentoo-specific-fix-install-locations-of-Ext-and-Mod.patch.xz to /tmp/portage/media-gfx/freecad-9999/work
>>> Source unpacked in /tmp/portage/media-gfx/freecad-9999/work
>>> Preparing source in /tmp/portage/media-gfx/freecad-9999/work/freecad-9999 ...
 * Source directory (CMAKE_USE_DIR): "/tmp/portage/media-gfx/freecad-9999/work/freecad-9999"
 * Build directory  (BUILD_DIR):     "/tmp/portage/media-gfx/freecad-9999/work/freecad-9999_build"
 * Applying freecad-0.19_pre20201231-0003-Gentoo-specific-don-t-check-vcs.patch ...                                                                                                                                                                    [ ok ]
 * Applying freecad-0.19.1-0001-Gentoo-specific-Remove-ccache-usage.patch ...                                                                                                                                                                          [ ok ]
 * Applying freecad-9999-Gentoo-specific-fix-install-locations-of-Ext-and-Mod.patch ...
patching file cMake/FreeCAD_Helpers/SetupShibokenAndPyside.cmake
patching file src/3rdParty/lazy_loader/CMakeLists.txt
patching file src/Gui/CMakeLists.txt
Hunk #1 succeeded at 1343 (offset 1 line).
patching file src/Mod/AddonManager/CMakeLists.txt
Hunk #1 succeeded at 42 (offset 3 lines).
patching file src/Mod/Arch/CMakeLists.txt
patching file src/Mod/Assembly/CMakeLists.txt
patching file src/Mod/Cam/CMakeLists.txt
patching file src/Mod/Cloud/CMakeLists.txt
patching file src/Mod/Complete/CMakeLists.txt
patching file src/Mod/Draft/CMakeLists.txt
patching file src/Mod/Drawing/CMakeLists.txt
patching file src/Mod/Fem/CMakeLists.txt
patching file src/Mod/Fem/Gui/CMakeLists.txt
Hunk #1 succeeded at 408 (offset 5 lines).
patching file src/Mod/Idf/CMakeLists.txt
patching file src/Mod/Image/CMakeLists.txt
patching file src/Mod/Import/CMakeLists.txt
patching file src/Mod/Inspection/CMakeLists.txt
patching file src/Mod/JtReader/CMakeLists.txt
patching file src/Mod/Material/CMakeLists.txt
patching file src/Mod/Measure/CMakeLists.txt
patching file src/Mod/Mesh/CMakeLists.txt
patching file src/Mod/MeshPart/CMakeLists.txt
patching file src/Mod/MeshPart/Gui/CMakeLists.txt
patching file src/Mod/OpenSCAD/CMakeLists.txt
patching file src/Mod/Part/CMakeLists.txt
Hunk #1 succeeded at 90 (offset 1 line).
patching file src/Mod/PartDesign/CMakeLists.txt
Hunk #1 succeeded at 103 (offset 1 line).
Hunk #2 succeeded at 185 (offset 1 line).
patching file src/Mod/Path/CMakeLists.txt
Hunk #1 succeeded at 22 (offset 2 lines).
Hunk #2 succeeded at 310 (offset 16 lines).
Hunk #3 FAILED at 323.
1 out of 3 hunks FAILED -- saving rejects to file src/Mod/Path/CMakeLists.txt.rej
patching file src/Mod/Plot/CMakeLists.txt
patching file src/Mod/Points/CMakeLists.txt
patching file src/Mod/Raytracing/CMakeLists.txt
patching file src/Mod/ReverseEngineering/CMakeLists.txt
patching file src/Mod/Robot/CMakeLists.txt
patching file src/Mod/Sandbox/CMakeLists.txt
patching file src/Mod/Show/CMakeLists.txt
patching file src/Mod/Sketcher/CMakeLists.txt
Hunk #1 succeeded at 47 (offset 1 line).
patching file src/Mod/Spreadsheet/CMakeLists.txt
patching file src/Mod/Start/CMakeLists.txt
patching file src/Mod/Start/StartPage/CMakeLists.txt
patching file src/Mod/Surface/CMakeLists.txt
patching file src/Mod/TechDraw/CMakeLists.txt
Hunk #1 succeeded at 68 (offset 21 lines).
Hunk #2 succeeded at 155 (offset 28 lines).
patching file src/Mod/TemplatePyMod/CMakeLists.txt
patching file src/Mod/Test/CMakeLists.txt
patching file src/Mod/Test/Gui/CMakeLists.txt
patching file src/Mod/Tux/CMakeLists.txt
patching file src/Mod/Web/CMakeLists.txt
patching file src/Tools/_TEMPLATE_/CMakeLists.txt                                                                                                                                                                                                      [ !! ]
 * ERROR: media-gfx/freecad-9999::waebbl failed (prepare phase):
 *   patch -p1  failed with /tmp/portage/media-gfx/freecad-9999/work/freecad-9999-Gentoo-specific-fix-install-locations-of-Ext-and-Mod.patch
 * 
 * Call stack:
 *               ebuild.sh, line  127:  Called src_prepare
 *             environment, line 3974:  Called eapply '/tmp/portage/media-gfx/freecad-9999/work/freecad-9999-Gentoo-specific-fix-install-locations-of-Ext-and-Mod.patch'
 *             environment, line 2081:  Called _eapply_patch '/tmp/portage/media-gfx/freecad-9999/work/freecad-9999-Gentoo-specific-fix-install-locations-of-Ext-and-Mod.patch'
 *             environment, line 2019:  Called __helpers_die 'patch -p1  failed with /tmp/portage/media-gfx/freecad-9999/work/freecad-9999-Gentoo-specific-fix-install-locations-of-Ext-and-Mod.patch'
 *   isolated-functions.sh, line  112:  Called die
 * The specific snippet of code:
 *   		die "$@"
 * 
 * If you need support, post the output of `emerge --info '=media-gfx/freecad-9999::waebbl'`,
 * the complete build log and the output of `emerge -pqv '=media-gfx/freecad-9999::waebbl'`.
 * The complete build log is located at '/tmp/portage/media-gfx/freecad-9999/temp/build.log'.
 * The ebuild environment file is located at '/tmp/portage/media-gfx/freecad-9999/temp/environment'.
 * Working directory: '/tmp/portage/media-gfx/freecad-9999/work/freecad-9999'
 * S: '/tmp/portage/media-gfx/freecad-9999/work/freecad-9999'

>>> Failed to emerge media-gfx/freecad-9999, Log file:

>>>  '/tmp/portage/media-gfx/freecad-9999/temp/build.log'

 * Messages for package media-gfx/freecad-9999:

 * ERROR: media-gfx/freecad-9999::waebbl failed (prepare phase):
 *   patch -p1  failed with /tmp/portage/media-gfx/freecad-9999/work/freecad-9999-Gentoo-specific-fix-install-locations-of-Ext-and-Mod.patch
 * 
 * Call stack:
 *               ebuild.sh, line  127:  Called src_prepare
 *             environment, line 3974:  Called eapply '/tmp/portage/media-gfx/freecad-9999/work/freecad-9999-Gentoo-specific-fix-install-locations-of-Ext-and-Mod.patch'
 *             environment, line 2081:  Called _eapply_patch '/tmp/portage/media-gfx/freecad-9999/work/freecad-9999-Gentoo-specific-fix-install-locations-of-Ext-and-Mod.patch'
 *             environment, line 2019:  Called __helpers_die 'patch -p1  failed with /tmp/portage/media-gfx/freecad-9999/work/freecad-9999-Gentoo-specific-fix-install-locations-of-Ext-and-Mod.patch'
 *   isolated-functions.sh, line  112:  Called die
 * The specific snippet of code:
 *   		die "$@"
 * 
 * If you need support, post the output of `emerge --info '=media-gfx/freecad-9999::waebbl'`,
 * the complete build log and the output of `emerge -pqv '=media-gfx/freecad-9999::waebbl'`.
 * The complete build log is located at '/tmp/portage/media-gfx/freecad-9999/temp/build.log'.
 * The ebuild environment file is located at '/tmp/portage/media-gfx/freecad-9999/temp/environment'.
 * Working directory: '/tmp/portage/media-gfx/freecad-9999/work/freecad-9999'
 * S: '/tmp/portage/media-gfx/freecad-9999/work/freecad-9999'

 * GNU info directory index is up-to-date.

**Comment by waebbl** [comment]
@evanfoss Sadly installing into `/usr` will become unmaintainable. That's why I decided to go back to installing into `/usr/$(get_libdir)/${PN}` instead. See the comment mentioned by @oli-nux. The update will most probably be ready today.

**Comment by waebbl** [comment]
> There is an issue with the freecad patchs in this ebuild. [build.log](https://github.com/waebbl/waebbl-gentoo/files/7916991/build.log)
> 
> Please fix the patchset.
> 
> > > > Emerging (2 of 2) media-gfx/freecad-9999::waebbl

@evanfoss For future reports, you can mark the output as code using triple backtick before and after the output (or a single backtick for in-text code snippets), to avoid the automatic formatting of github and make the report more readable. Thank you!

**Comment by exonitocris** [comment]
@waebbl thx for your great work & effort in gentoo community. 

Do you see any chance of getting some/all these patched **CMakeList.txt** files **upstream** and get rid of all these patching stuff in regard to installation dir locations?

**Comment by waebbl** [comment]
> @waebbl thx for your great work & effort in gentoo community.
> 
> Do you see any chance of getting some/all these patched **CMakeList.txt** files **upstream** and get rid of all these patching stuff in regard to installation dir locations?

I'm very sceptical on this. See https://github.com/waebbl/waebbl-gentoo/issues/354#issuecomment-1013860556 and the linked forum topic there for a discussion on this. I'm still thinking on branching and trying to implement this, and re-open the discussion.
My latest push reverted back to installing into `/usr/$(get_libdir)/${PN}` to keep the live ebuild maintainable.

**Comment by exonitocris** [comment]
@waebbl sorry for not searching accurately before asking!!! thx for the links!

**Comment by waebbl** [comment]
@exonitocris No worries. The topic was well hidden ;)

**Comment by evanfoss** [comment]
Thanks for fixing this and for maintaining the ebuild in the first place. Now it makes no difference to me but what drove the changes to the install location you were talking about, was that a gentoo thing or an issue with freecad?

**Comment by evanfoss** [comment]
> > There is an issue with the freecad patchs in this ebuild. [build.log](https://github.com/waebbl/waebbl-gentoo/files/7916991/build.log)
> > Please fix the patchset.
> > > > > Emerging (2 of 2) media-gfx/freecad-9999::waebbl
> 
> @evanfoss For future reports, you can mark the output as code using triple backtick before and after the output (or a single backtick for in-text code snippets), to avoid the automatic formatting of github and make the report more readable. Thank you!

Ok sorry.
