### ISSUE TITLE
freecad-9999: no more ChangeLog.txt

### ISSUE THREAD

**Issue by khumarahn** [waebbl/waebbl-gentoo#372]
Hi. The file `ChangeLog.txt` does not exits anymore, at least where it used to be. This causes the ebuild to fail.

https://github.com/waebbl/waebbl-gentoo/blob/f7a973d71f0ae9dcec2cc8ed83e7b867a059d8c4/media-gfx/freecad/freecad-9999.ebuild#L129

**Comment by waebbl** [comment]
Please use the live ebuild from ::gentoo. The ebuild on my overlay is mainly used to develop new features and is not meant for general use anymore. It's not updated regularly.

**Comment by khumarahn** [comment]
I wanted actually to ping you about the ebuild in gentoo, where the same thing happens. I thought maybe you have a quick way of fixing that, and wasn't sure if I should create a bug for a live ebuild

**Comment by waebbl** [comment]
Yes please file a bug in b.g.o. if it happens on the ::gentoo live ebuild as well. Thanks for report! Haven't build the package for a week or two, so this is likely a very recent change.

**Comment by waebbl** [comment]
A quick way to fix it, is to remove the filename from the `DOCS=` line in the ebuild.

**Comment by khumarahn** [comment]
thanks a lot!! yes, I realized that I could remove that filename :-)
