### ISSUE TITLE
pyside-9999 fails to build

### ISSUE THREAD

**Issue by kamikaze** [waebbl/waebbl-gentoo#51]
-- <<< Gentoo configuration >>>
Build type      Gentoo
Install path    /usr
Compiler flags:
C               -O2 -pipe -march=native -mtune=native
C++             -O2 -pipe -march=native -mtune=native -Wall -fvisibility=hidden -Wno-strict-aliasing
Linker flags:
Executable      -Wl,-O1 -Wl,--as-needed
Module          -Wl,-O1 -Wl,--as-needed
Shared          -Wl,-O1 -Wl,--as-needed

-- Configuring done
CMake Error at cmake/Macros/PySideModules.cmake:113 (add_dependencies):
  The dependency target "QtMultimedia" of target "QtTextToSpeech" does not
  exist.
Call Stack (most recent call first):
  PySide2/QtTextToSpeech/CMakeLists.txt:29 (create_pyside_module)

-- Generating done
CMake Warning:
  Manually-specified variables were not used by the project:

    CMAKE_DISABLE_FIND_PACKAGE_Qt5WebKit
    CMAKE_DISABLE_FIND_PACKAGE_Qt5WebKitWidgets

**Comment by kamikaze** [comment]
this happens when I have no multimedia USE flag set

**Comment by waebbl** [comment]
Thanks for reporting this.

**Comment by waebbl** [comment]
@kamikaze is this bug still valid?

**Comment by ramast** [comment]
Can confirm still valid.

My use flags

`[ebuild  N    *] dev-python/pyside-9999:2::qt  USE="gui network opengl svg webchannel webengine widgets -charts -concurrent -datavis -declarative -designer -help -multimedia -printsupport -script -scripttools -sql -test -testlib -webkit -websockets -x11extras -xmlpatterns" PYTHON_TARGETS="python2_7 python3_6 -python3_5" 0 KiB`

The error

```
-- Configuring done
CMake Error at cmake/Macros/PySideModules.cmake:113 (add_dependencies):
  The dependency target "QtMultimedia" of target "QtTextToSpeech" does not
  exist.
Call Stack (most recent call first):
  PySide2/QtTextToSpeech/CMakeLists.txt:29 (create_pyside_module)
```

**Comment by waebbl** [comment]
@ramast Your output says, you're trying to use the ebuild from `::qt` overlay. It differs in USE flags, from the one in my overlay. Can you also confirm it to fail with the `pyside-9999::waebbl` ebuild?

Also there's been an IN_P bug on b.g.o https://bugs.gentoo.org/624682, just in case you're not aware of it.

**Comment by ramast** [comment]
I've followed @kamikaze 's hint and compiled successfully with the media flag.
I am afraid I don't have the waebbl overlay to test this one.

I came to this page by google the error I got, I didn't realize its a different overlay.

I guess you could ignore my comment :)

**Comment by waebbl** [comment]
@ramast ok, so I'm closing this issue
