### ISSUE TITLE
pyside-9999 fails to install

### ISSUE THREAD

**Issue by kamikaze** [waebbl/waebbl-gentoo#52]
-- Installing: /var/tmp/portage/dev-python/pyside-9999/image/usr/include/PySide2/Qt3DExtras/pyside2_qt3dextras_python.h
-- Installing: /var/tmp/portage/dev-python/pyside-9999/image/usr/share/PySide2/typesystems/typesystem_3dextras.xml
mv: cannot stat '/var/tmp/portage/dev-python/pyside-9999/imageusr/lib64/pkgconfig/pyside2.pc': No such file or directory

**Comment by waebbl** [comment]
Thanks for reporting it. Looks like an issue which is tied to my bump to EAPI 7 lately. If you like, you can change the `mv` line in `src_install` so it reads `mv "${ED}"/usr/$(get_libdir)/...` with an added `/` before the `usr/` to try to fix this. Feel free to open a PR if it works.

**Comment by Moult** [comment]
I am experiencing this for dev-python/pyside-5.11.1 as well. Your fix of adding a `/` before `usr/` works :) I didn't create a PR, but I can guarantee it works :)

**Comment by waebbl** [comment]
@Moult thanks for testing it. I already fixed it in my local repo and know it's working, but couldn't push it due to some other issues which have risen up in the meantime.

**Comment by waebbl** [comment]
@kamikaze Should have been fixed by https://github.com/waebbl/waebbl-gentoo/pull/57.
Feel free to reopen if the bug still exists.
