### ISSUE TITLE
freecad patch for boost-1.69

### ISSUE THREAD

**Issue by brothermechanic** [waebbl/waebbl-gentoo#55]
Hello
Please update freecad for building with boost-1.69
This patch may be useful (i can't apply it)
https://svnweb.freebsd.org/ports/head/cad/freecad/files/patch-boost-1.69?view=log

**Comment by waebbl** [comment]
Hi @brothermechanic, I don't have any boost-1.69 around in any of the overlays I use. So I won't fix this, until boost finds it's way into the main tree. The latest version I have is 1.67.0-r1, but it's hard-masked like 1.66.0 is, so there's serious issues with those releases. 
I also haven't seen a single package yet, which seriously **needed** boost > 1.67.

**Comment by brothermechanic** [comment]
sad, my openvdb build only with boost-1.68 and 1.69

**Comment by brothermechanic** [comment]
cool, hope you can fix it!
ps: my openvdb builds only with boost-1.68 and 1.69

**Comment by waebbl** [comment]
Closing this, as boost-1.69 is no longer in the tree.
