### ISSUE TITLE
libmed blocking med-fichier + different hdf5 versions for dependencies

### ISSUE THREAD

**Issue by alexanderustinov** [waebbl/waebbl-gentoo#65]
Greetings, after recent sync of repository world update stucks at

> <-- cut -->
> [blocks B      ] sci-libs/libmed ("sci-libs/libmed" is blocking sci-libs/med-fichier-4.0.0)
> 
> !!! Multiple package instances within a single package slot have been pulled
> !!! into the dependency graph, resulting in a slot conflict:
> 
> sci-libs/hdf5:0
> 
>   (sci-libs/hdf5-1.10.4:0/1.10.4::waebbl, ebuild scheduled for merge) pulled in by
>     >=sci-libs/hdf5-1.10.2:=[fortran=,mpi=] required by (sci-libs/med-fichier-4.0.0:0/0::waebbl, ebuild scheduled for merge)
>     ^^              ^^^^^^                                                                                                                                                                            
> 
>   (sci-libs/hdf5-1.8.18:0/1.8.18::gentoo, installed) pulled in by
>     sci-libs/hdf5:0/1.8.18=[hl(+),-mpi,-szip,zlib] required by (sci-libs/netcdf-4.6.1-r1:0/13::gentoo, installed)
>                  ^^^^^^^^^^                                                                                                                          
>     (and 1 more with the same problem)
> 
> <-- cut -->
> 
>  * Error: The above package list contains packages which cannot be
>  * installed at the same time on the same system.
> 
>   (sci-libs/libmed-3.3.1-r1:0/0::waebbl, ebuild scheduled for merge) pulled in by
>     sci-libs/libmed:=[fortran,python,python_targets_python3_6(-)?,-python_single_target_jython2_7(-),-python_single_target_pypy(-),-python_single_target_pypy3(-),-python_single_target_python2_7(-),-python_single_target_python3_4(-),-python_single_target_python3_5(-),-python_single_target_python3_7(-),python_single_target_python3_6(+)] (sci-libs/libmed:=[fortran,python,python_targets_python3_6(-),-python_single_target_jython2_7(-),-python_single_target_pypy(-),-python_single_target_pypy3(-),-python_single_target_python2_7(-),-python_single_target_python3_4(-),-python_single_target_python3_5(-),-python_single_target_python3_7(-),python_single_target_python3_6(+)]) required by (media-gfx/freecad-9999:0/0::waebbl, installed)
> 
>   (sci-libs/med-fichier-4.0.0:0/0::waebbl, ebuild scheduled for merge) pulled in by
>     sci-libs/med-fichier:0/0=[fortran,python,python_targets_python3_6(-),-python_single_target_jython2_7(-),-python_single_target_pypy(-),-python_single_target_pypy3(-),-python_single_target_python2_7(-),-python_single_target_python3_4(-),-python_single_target_python3_5(-),-python_single_target_python3_7(-),python_single_target_python3_6(+)] required by (media-gfx/freecad-9999:0/0::waebbl, installed)

**Comment by waebbl** [comment]
Hi this should have been fixed by https://github.com/waebbl/waebbl-gentoo/pull/68

**Comment by alexanderustinov** [comment]
Indeed it is, thank you.

**Comment by waebbl** [comment]
Sorry for the inconveniece, I pushed the libmed / med-fichier update by mistake, while the revdeps were not yet fixed. Thanks for reporting the issue and testing the repo :)
