### ISSUE TITLE
sci-libs/libmed-3.3.1::waebbl failed

### ISSUE THREAD

**Issue by brothermechanic** [waebbl/waebbl-gentoo#7]
HDF5 version is 1.10.1.  Only 1.8.x versions are supported.
You can use my ebuild)

**Comment by waebbl** [comment]
Now I remember why I decided to remove the file. It's too big, far too big and libmed compiled with hdf-1.8 just fine.
Do you really need the hdf5-1.10? I would have to split the hdf5 patch into about 15 separate files, because patches in ${FILESDIR} must not be bigger than 20kb, IIRC. I cannot commit the ebuild with this patch, because repoman complains with a fatal error.

**Comment by waebbl** [comment]
So I decided to put the hdf5 patch file onto my github webspace at waebbl.github.io and included it in the ebuild.
Would you please pull the changes and try check whether it's compiling with hdf5-1.10?
Thank you! :)

**Comment by waebbl** [comment]
You are free to use your own libmed, of course. It's just I can't use your patch in my overlay, because repoman won't let me commit it.

**Comment by waebbl** [comment]
BTW is your libmed working from within python? Try this

```
import med
```

from within python.

What error do you get, if you try to compile freecad against libmed?

**Comment by brothermechanic** [comment]
Hello
May be we dont need this package? in freecad sources there is libmed too
Import med get error, dont work
This is my libmed files https://paste.pound-python.org/show/CBomD1gSTz6w78FPMtl3/

**Comment by waebbl** [comment]
I want to exclude as much as possible from the freecad and using system provided packages instead. If you look at my todo list, you will see, that I want to include more external packages, which are currently shipped with freecad, for example smesh but also others.

On my machine freecad compiles well with my ebuild. Just did a recompile this morning with the lastest master. So please tell me, what error do you get when building freecad against libmed?

>This is my libmed files https://paste.pound-python.org/show/CBomD1gSTz6w78FPMtl3/

Mine is almost equal, but I have an additional doc directory. What I'm not happy with is the header files. Having a /usr/include/2.3.6 subdir is like having a /usr/include/blah subdirectory. Nobody knows where it's coming from, nobody knows what it is. I want to move the header files into a separate subdir like /usr/include/libmed, but it doesn't have a high priority and has to wait.

**Comment by waebbl** [comment]
I updated some things in the ebuild. Could you please try to re-compile and whether python bindings are working?

**Comment by waebbl** [comment]
This issue has become obsolete with the new 4.0.0 version of libmed.
Closing it. Feel free to reopen it, if it pops up again.
